# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import sqlserver_ado.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('idalertas', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idAlertas', primary_key=True)),
                ('tipo', models.CharField(db_column='Tipo', max_length=60, blank=True)),
            ],
            options={
                'db_table': 'Alertas',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AlertasCuenta',
            fields=[
                ('idalertascuenta', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idAlertasCuenta', primary_key=True)),
                ('valor', models.BigIntegerField(db_column='Valor')),
                ('alertas_idalertas', models.ForeignKey(db_column='Alertas_idAlertas', to='Matcher.Alertas')),
            ],
            options={
                'db_table': 'Alertas_Cuenta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AlertasCuentaBk',
            fields=[
                ('idalertascuenta', models.BigIntegerField(serialize=False, db_column='idAlertasCuenta', primary_key=True)),
                ('alertas_bk_idalertas', models.BigIntegerField(db_column='Alertas_BK_idAlertas')),
                ('valor', models.BigIntegerField(db_column='Valor')),
            ],
            options={
                'db_table': 'Alertas_Cuenta_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BancoCorresponsal',
            fields=[
                ('idbanco', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idBanco', primary_key=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=10)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'db_table': 'Banco_Corresponsal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Codigo95',
            fields=[
                ('idcodigo95', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idCodigo95', primary_key=True)),
                ('codigo', models.BigIntegerField(db_column='Codigo', null=True, blank=True)),
                ('help', models.TextField(db_column='Help')),
            ],
            options={
                'db_table': 'Codigo95',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Codigo96',
            fields=[
                ('idcodigo96', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idCodigo96', primary_key=True)),
                ('codigo', models.BigIntegerField(db_column='Codigo')),
                ('help', models.TextField(db_column='Help')),
            ],
            options={
                'db_table': 'Codigo96',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Conciliacionconsolidado',
            fields=[
                ('idconciliacionconsolidado', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idConciliacionConsolidado', primary_key=True)),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('realizadopor', models.CharField(db_column='RealizadoPor', max_length=60, blank=True)),
            ],
            options={
                'db_table': 'ConciliacionConsolidado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ConciliacionconsolidadoBk',
            fields=[
                ('idconciliacionconsolidado', models.BigIntegerField(serialize=False, db_column='idConciliacionConsolidado', primary_key=True)),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('realizadopor', models.CharField(db_column='RealizadoPor', max_length=60, blank=True)),
            ],
            options={
                'db_table': 'ConciliacionConsolidado_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('idconfiguracion', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idConfiguracion', primary_key=True)),
                ('idioma', models.IntegerField(db_column='Idioma')),
                ('archcontabilidadcarg', models.CharField(db_column='ArchContabilidadCarg', max_length=200)),
                ('archcontabilidadproc', models.CharField(db_column='ArchContabilidadProc', max_length=200)),
                ('archswiftcarg', models.CharField(db_column='ArchSwiftCarg', max_length=200)),
                ('archswiftproc', models.CharField(db_column='ArchSwiftProc', max_length=200)),
                ('bdhost', models.CharField(db_column='BDHost', max_length=200)),
                ('bddriver', models.CharField(db_column='BDDriver', max_length=200)),
                ('bdnombre', models.CharField(db_column='BDNombre', max_length=50)),
                ('bdpuerto', models.IntegerField(db_column='BDPuerto')),
                ('bdusuario', models.CharField(db_column='BDUsuario', max_length=50)),
                ('bdpass', models.CharField(db_column='BDPass', max_length=50)),
                ('alertasservidor', models.CharField(db_column='AlertasServidor', max_length=200, blank=True)),
                ('alertaspuerto', models.IntegerField(db_column='AlertasPuerto', null=True, blank=True)),
                ('alertasusuario', models.CharField(db_column='AlertasUsuario', max_length=50, blank=True)),
                ('alertaspass', models.CharField(db_column='AlertasPass', max_length=50, blank=True)),
                ('tiemporetentrazas', models.IntegerField(db_column='TiempoRetenTrazas', null=True, blank=True)),
                ('matcherhost', models.CharField(db_column='MatcherHost', max_length=200, blank=True)),
                ('matcherpuerto', models.IntegerField(db_column='MatcherPuerto', null=True, blank=True)),
                ('caducidad', models.IntegerField(db_column='Caducidad', null=True, blank=True)),
                ('longitud_minima', models.IntegerField(db_column='Longitud_Minima', null=True, blank=True)),
                ('num_intentos', models.IntegerField(db_column='Num_Intentos', null=True, blank=True)),
                ('num_passrecordar', models.IntegerField(db_column='Num_PassRecordar', null=True, blank=True)),
                ('caracteresespeciales', models.IntegerField(db_column='CaracteresEspeciales', null=True, blank=True)),
                ('numeros', models.IntegerField(db_column='Numeros', null=True, blank=True)),
                ('mayusculas', models.IntegerField(db_column='Mayusculas', null=True, blank=True)),
                ('alfabeticos', models.IntegerField(db_column='Alfabeticos', null=True, blank=True)),
                ('dirarchive', models.CharField(db_column='DirArchive', max_length=200, blank=True)),
                ('dirsalida95', models.CharField(db_column='DirSalida95', max_length=200, blank=True)),
                ('dircarga96', models.CharField(db_column='DirCarga96', max_length=200, blank=True)),
                ('dircarga99', models.CharField(db_column='DirCarga99', max_length=200, blank=True)),
                ('dirsalida99', models.CharField(db_column='DirSalida99', max_length=200, blank=True)),
                ('bic', models.CharField(db_column='Bic', max_length=200, blank=True)),
                ('ldap_ip', models.CharField(db_column='LDAP_IP', max_length=20, blank=True)),
                ('ldap_puerto', models.CharField(db_column='LDAP_Puerto', max_length=15, blank=True)),
                ('ldap_dominio', models.CharField(db_column='LDAP_Dominio', max_length=50, blank=True)),
            ],
            options={
                'db_table': 'Configuracion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CriteriosMatch',
            fields=[
                ('idcriterio', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idCriterio', primary_key=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('num_entradas', models.BigIntegerField(db_column='Num_Entradas')),
                ('monto1', models.FloatField(db_column='Monto1', null=True, blank=True)),
                ('monto2', models.FloatField(db_column='Monto2', null=True, blank=True)),
                ('monto3', models.FloatField(db_column='Monto3', null=True, blank=True)),
                ('fecha1', models.IntegerField(db_column='Fecha1', null=True, blank=True)),
                ('fecha2', models.IntegerField(db_column='Fecha2', null=True, blank=True)),
                ('fecha3', models.IntegerField(db_column='Fecha3', null=True, blank=True)),
                ('fecha4', models.IntegerField(db_column='Fecha4', null=True, blank=True)),
                ('fecha5', models.IntegerField(db_column='Fecha5', null=True, blank=True)),
            ],
            options={
                'db_table': 'Criterios_Match',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idcuenta', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idCuenta', primary_key=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=10)),
                ('ref_nostro', models.CharField(db_column='Ref_Nostro', max_length=35)),
                ('ref_vostro', models.CharField(db_column='Ref_Vostro', max_length=35)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, blank=True)),
                ('estado', models.CharField(db_column='Estado', max_length=10)),
                ('tiempo_retension', models.IntegerField(db_column='Tiempo_Retension')),
                ('num_saltos', models.IntegerField(db_column='Num_Saltos')),
                ('transaccion_giro', models.CharField(db_column='Transaccion_Giro', max_length=20, blank=True)),
                ('intraday', models.CharField(db_column='Intraday', max_length=1, blank=True)),
                ('correo_alertas', models.CharField(db_column='Correo_Alertas', max_length=45, blank=True)),
                ('montoencajeactual', models.FloatField(db_column='MontoEncajeActual', null=True, blank=True)),
                ('fechaencajeactual', models.DateTimeField(db_column='FechaEncajeActual', null=True, blank=True)),
                ('ultimafechaconciliacion', models.DateTimeField(db_column='UltimaFechaConciliacion', null=True, blank=True)),
                ('ultimoedocuentacargs', models.BigIntegerField(db_column='UltimoEdoCuentaCargS', null=True, blank=True)),
                ('ultimoedocuentaprocs', models.BigIntegerField(db_column='UltimoEdoCuentaProcS', null=True, blank=True)),
                ('ultimoedocuentacargc', models.BigIntegerField(db_column='UltimoEdoCuentaCargC', null=True, blank=True)),
                ('ultimoedocuentaprocc', models.BigIntegerField(db_column='UltimoEdoCuentaProcC', null=True, blank=True)),
                ('concurrencia', models.IntegerField(db_column='Concurrencia', null=True, blank=True)),
                ('ultimafechahistorico', models.DateTimeField(db_column='UltimaFechaHistorico', null=True, blank=True)),
                ('tipo_cta', models.IntegerField(db_column='Tipo_Cta', null=True, blank=True)),
                ('tipo_cargacont', models.IntegerField(db_column='Tipo_CargaCont', null=True, blank=True)),
                ('tipo_carga_corr', models.IntegerField(db_column='Tipo_Carga_Corr', null=True, blank=True)),
                ('tipo_proceso', models.IntegerField(db_column='Tipo_Proceso', null=True, blank=True)),
                ('zona', models.CharField(db_column='Zona', max_length=100, blank=True)),
            ],
            options={
                'db_table': 'Cuenta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CuentaBk',
            fields=[
                ('idcuenta', models.BigIntegerField(serialize=False, db_column='idCuenta', primary_key=True)),
                ('criterios_match_bk_idcriterio', models.BigIntegerField(db_column='Criterios_Match_BK_idCriterio')),
                ('banco_corresponsal_bk_idbanco', models.BigIntegerField(db_column='Banco_Corresponsal_BK_idBanco')),
                ('codigo', models.CharField(db_column='Codigo', max_length=10)),
                ('moneda_bk_idmoneda', models.BigIntegerField(db_column='Moneda_BK_idMoneda', null=True, blank=True)),
                ('ref_nostro', models.CharField(db_column='Ref_Nostro', max_length=35)),
                ('ref_vostro', models.CharField(db_column='Ref_Vostro', max_length=35)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, blank=True)),
                ('estado', models.CharField(db_column='Estado', max_length=10)),
                ('tiempo_retension', models.IntegerField(db_column='Tiempo_Retension')),
                ('num_saltos', models.IntegerField(db_column='Num_Saltos')),
                ('transaccion_giro', models.CharField(db_column='Transaccion_Giro', max_length=20, blank=True)),
                ('intraday', models.CharField(db_column='Intraday', max_length=1, blank=True)),
                ('correo_alertas', models.CharField(db_column='Correo_Alertas', max_length=45, blank=True)),
                ('montoencajeactual', models.FloatField(db_column='MontoEncajeActual', null=True, blank=True)),
                ('fechaencajeactual', models.DateTimeField(db_column='FechaEncajeActual', null=True, blank=True)),
                ('ultimafechaconciliacion', models.DateTimeField(db_column='UltimaFechaConciliacion', null=True, blank=True)),
                ('ultimoedocuentacargs', models.BigIntegerField(db_column='UltimoEdoCuentaCargS', null=True, blank=True)),
                ('ultimoedocuentaprocs', models.BigIntegerField(db_column='UltimoEdoCuentaProcS', null=True, blank=True)),
                ('ultimoedocuentacargc', models.BigIntegerField(db_column='UltimoEdoCuentaCargC', null=True, blank=True)),
                ('ultimoedocuentaprocc', models.BigIntegerField(db_column='UltimoEdoCuentaProcC', null=True, blank=True)),
                ('concurrencia', models.IntegerField(db_column='Concurrencia', null=True, blank=True)),
                ('ultimafechahistorico', models.DateTimeField(db_column='UltimaFechaHistorico', null=True, blank=True)),
                ('tipo_cta', models.IntegerField(db_column='Tipo_Cta', null=True, blank=True)),
                ('tipo_cargacont', models.IntegerField(db_column='Tipo_CargaCont', null=True, blank=True)),
                ('tipo_carga_corr', models.IntegerField(db_column='Tipo_Carga_Corr', null=True, blank=True)),
                ('tipo_proceso', models.IntegerField(db_column='Tipo_Proceso', null=True, blank=True)),
                ('zona', models.CharField(db_column='Zona', max_length=100, blank=True)),
            ],
            options={
                'db_table': 'Cuenta_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='Id_Empresa', primary_key=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('dir_logo', models.CharField(db_column='Dir_Logo', max_length=200)),
                ('nombregrupo', models.CharField(db_column='NombreGrupo', max_length=50)),
                ('direccion', models.CharField(db_column='Direccion', max_length=150)),
                ('creditoscontabilidad', models.CharField(db_column='CreditosContabilidad', max_length=60)),
                ('debitoscontabilidad', models.CharField(db_column='DebitosContabilidad', max_length=60)),
                ('creditoscorresponsal', models.CharField(db_column='CreditosCorresponsal', max_length=60)),
                ('debitoscorresponsal', models.CharField(db_column='DebitosCorresponsal', max_length=60)),
                ('pais', models.CharField(db_column='Pais', max_length=15)),
                ('autorizadopor', models.CharField(db_column='AutorizadoPor', max_length=60, blank=True)),
                ('firmadopor', models.CharField(db_column='FirmadoPor', max_length=60, blank=True)),
                ('cargofirmante', models.CharField(db_column='CargoFirmante', max_length=60, blank=True)),
            ],
            options={
                'db_table': 'Empresa',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Encajelegal',
            fields=[
                ('idencajelegal', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idEncajeLegal', primary_key=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'EncajeLegal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EncajelegalBk',
            fields=[
                ('idencajelegal', models.BigIntegerField(serialize=False, db_column='idEncajeLegal', primary_key=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'EncajeLegal_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('idedocuenta', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idEdoCuenta', primary_key=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=35)),
                ('origen', models.CharField(db_column='Origen', max_length=1)),
                ('pagina', models.BigIntegerField(db_column='Pagina')),
                ('balance_inicial', models.FloatField(db_column='Balance_Inicial')),
                ('balance_final', models.FloatField(db_column='Balance_Final')),
                ('m_finicial', models.CharField(db_column='M_Finicial', max_length=1)),
                ('m_ffinal', models.CharField(db_column='M_Ffinal', max_length=1)),
                ('fecha_inicial', models.DateTimeField(db_column='Fecha_Inicial')),
                ('fecha_final', models.DateTimeField(db_column='Fecha_Final')),
                ('c_dinicial', models.CharField(db_column='C_DInicial', max_length=1)),
                ('c_dfinal', models.CharField(db_column='C_DFinal', max_length=1)),
                ('idbk', models.BigIntegerField(db_column='idBK', null=True, blank=True)),
            ],
            options={
                'db_table': 'Estado_Cuenta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cargado',
            fields=[
                ('estado_cuenta_idedocuenta', models.ForeignKey(serialize=False, primary_key=True, to='Matcher.EstadoCuenta', db_column='Estado_Cuenta_idEdoCuenta')),
            ],
            options={
                'db_table': 'Cargado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EstadoCuentaBk',
            fields=[
                ('idedocuenta', models.BigIntegerField(serialize=False, db_column='idEdoCuenta', primary_key=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=35)),
                ('origen', models.CharField(db_column='Origen', max_length=1)),
                ('pagina', models.BigIntegerField(db_column='Pagina')),
                ('balance_inicial', models.FloatField(db_column='Balance_Inicial')),
                ('balance_final', models.FloatField(db_column='Balance_Final')),
                ('m_finicial', models.CharField(db_column='M_Finicial', max_length=1)),
                ('m_ffinal', models.CharField(db_column='M_Ffinal', max_length=1)),
                ('fecha_inicial', models.DateTimeField(db_column='Fecha_Inicial')),
                ('fecha_final', models.DateTimeField(db_column='Fecha_Final')),
                ('c_dinicial', models.CharField(db_column='C_DInicial', max_length=1)),
                ('c_dfinal', models.CharField(db_column='C_DFinal', max_length=1)),
                ('idbk', models.BigIntegerField(db_column='idBK', null=True, blank=True)),
            ],
            options={
                'db_table': 'Estado_Cuenta_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CargadoBk',
            fields=[
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(serialize=False, primary_key=True, to='Matcher.EstadoCuentaBk', db_column='Estado_Cuenta_BK_idEdoCuenta')),
            ],
            options={
                'db_table': 'Cargado_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.IntegerField(serialize=False, db_column='IdEvento', primary_key=True)),
                ('accion', models.CharField(db_column='Accion', max_length=45)),
            ],
            options={
                'db_table': 'Evento',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Formatoarchivo',
            fields=[
                ('idformato', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idFormato', primary_key=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('separador', models.CharField(db_column='Separador', max_length=2)),
                ('tipo', models.CharField(db_column='Tipo', max_length=2)),
                ('formato', models.CharField(db_column='Formato', max_length=20)),
            ],
            options={
                'db_table': 'FormatoArchivo',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FormatoarchivoBk',
            fields=[
                ('idformato', models.BigIntegerField(serialize=False, db_column='idFormato', primary_key=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('separador', models.CharField(db_column='Separador', max_length=2)),
                ('tipo', models.CharField(db_column='Tipo', max_length=2)),
                ('formato', models.CharField(db_column='Formato', max_length=20)),
            ],
            options={
                'db_table': 'FormatoArchivo_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Historicoconsolidado',
            fields=[
                ('idhistoricoconsolidado', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idHistoricoConsolidado', primary_key=True)),
                ('fechaconciliacion', models.DateTimeField(db_column='FechaConciliacion')),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('autorizadopor', models.CharField(db_column='AutorizadoPor', max_length=60, blank=True)),
                ('firmadopor', models.CharField(db_column='FirmadoPor', max_length=60, blank=True)),
                ('cargofirmante', models.CharField(db_column='CargoFirmante', max_length=60, blank=True)),
                ('realizadopor', models.CharField(db_column='RealizadoPor', max_length=60, blank=True)),
                ('numedo_cont', models.CharField(db_column='NumEdo_Cont', max_length=35, blank=True)),
                ('pag_cont', models.IntegerField(db_column='Pag_Cont', null=True, blank=True)),
                ('fecha_cont', models.DateTimeField(db_column='Fecha_Cont', null=True, blank=True)),
                ('balance_cont', models.FloatField(db_column='Balance_Cont', null=True, blank=True)),
                ('cd_cont', models.CharField(db_column='CD_Cont', max_length=1, blank=True)),
                ('numedo_corr', models.CharField(db_column='NumEdo_Corr', max_length=35, blank=True)),
                ('pag_corr', models.IntegerField(db_column='Pag_Corr', null=True, blank=True)),
                ('fecha_corr', models.DateTimeField(db_column='Fecha_Corr', null=True, blank=True)),
                ('balance_corr', models.FloatField(db_column='Balance_Corr', null=True, blank=True)),
                ('cd_corr', models.CharField(db_column='CD_Corr', max_length=1, blank=True)),
                ('tasa_cambio', models.FloatField(db_column='Tasa_Cambio', null=True, blank=True)),
            ],
            options={
                'db_table': 'HistoricoConsolidado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HistoricoconsolidadoBk',
            fields=[
                ('idhistoricoconsolidado', models.BigIntegerField(serialize=False, db_column='idHistoricoConsolidado', primary_key=True)),
                ('fechaconciliacion', models.DateTimeField(db_column='FechaConciliacion')),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('autorizadopor', models.CharField(db_column='AutorizadoPor', max_length=60, blank=True)),
                ('firmadopor', models.CharField(db_column='FirmadoPor', max_length=60, blank=True)),
                ('cargofirmante', models.CharField(db_column='CargoFirmante', max_length=60, blank=True)),
                ('realizadopor', models.CharField(db_column='RealizadoPor', max_length=60, blank=True)),
                ('numedo_cont', models.CharField(db_column='NumEdo_Cont', max_length=35, blank=True)),
                ('pag_cont', models.IntegerField(db_column='Pag_Cont', null=True, blank=True)),
                ('fecha_cont', models.DateTimeField(db_column='Fecha_Cont', null=True, blank=True)),
                ('balance_cont', models.FloatField(db_column='Balance_Cont', null=True, blank=True)),
                ('cd_cont', models.CharField(db_column='CD_Cont', max_length=1, blank=True)),
                ('numedo_corr', models.CharField(db_column='NumEdo_Corr', max_length=35, blank=True)),
                ('pag_corr', models.IntegerField(db_column='Pag_Corr', null=True, blank=True)),
                ('fecha_corr', models.DateTimeField(db_column='Fecha_Corr', null=True, blank=True)),
                ('balance_corr', models.FloatField(db_column='Balance_Corr', null=True, blank=True)),
                ('cd_corr', models.CharField(db_column='CD_Corr', max_length=1, blank=True)),
                ('tasa_cambio', models.FloatField(db_column='Tasa_Cambio', null=True, blank=True)),
            ],
            options={
                'db_table': 'HistoricoConsolidado_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Historicotransacciones',
            fields=[
                ('idhistoricotransacciones', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idHistoricoTransacciones', primary_key=True)),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('refvostro', models.CharField(db_column='RefVostro', max_length=16, blank=True)),
                ('refnostro', models.CharField(db_column='RefNostro', max_length=16, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('origen', models.CharField(db_column='Origen', max_length=1)),
                ('observacion', models.CharField(db_column='Observacion', max_length=300, blank=True)),
                ('num_transaccion', models.IntegerField(db_column='Num_Transaccion')),
                ('fecha_salida', models.DateTimeField(db_column='Fecha_Salida', null=True, blank=True)),
                ('numedo', models.CharField(db_column='NumEdo', max_length=35, blank=True)),
                ('historicoconsolidado', models.ForeignKey(db_column='HistoricoConsolidado_ID', to='Matcher.Historicoconsolidado')),
            ],
            options={
                'db_table': 'HistoricoTransacciones',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HistoricotransaccionesBk',
            fields=[
                ('idhistoricotransacciones', models.BigIntegerField(serialize=False, db_column='idHistoricoTransacciones', primary_key=True)),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('refvostro', models.CharField(db_column='RefVostro', max_length=16, blank=True)),
                ('refnostro', models.CharField(db_column='RefNostro', max_length=16, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('origen', models.CharField(db_column='Origen', max_length=1)),
                ('observacion', models.CharField(db_column='Observacion', max_length=300, blank=True)),
                ('num_transaccion', models.IntegerField(db_column='Num_Transaccion')),
                ('fecha_salida', models.DateTimeField(db_column='Fecha_Salida', null=True, blank=True)),
                ('numedo', models.CharField(db_column='NumEdo', max_length=35, blank=True)),
                ('historicoconsolidado_bk', models.ForeignKey(db_column='HistoricoConsolidado_BK_ID', to='Matcher.HistoricoconsolidadoBk')),
            ],
            options={
                'db_table': 'HistoricoTransacciones_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('ididioma', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idIdioma', primary_key=True)),
                ('espanol', models.CharField(db_column='Espanol', max_length=200)),
                ('ingles', models.CharField(db_column='Ingles', max_length=200)),
            ],
            options={
                'db_table': 'Idioma',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Matchconfirmado',
            fields=[
                ('idmatch', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idMatch', primary_key=True)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(db_column='Justificacion', max_length=100, blank=True)),
                ('codigomatch', models.CharField(db_column='CodigoMatch', max_length=20)),
                ('tipo_proceso', models.IntegerField(db_column='Tipo_Proceso', null=True, blank=True)),
            ],
            options={
                'db_table': 'MatchConfirmado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MatchconfirmadoBk',
            fields=[
                ('idmatch', models.BigIntegerField(serialize=False, db_column='idMatch', primary_key=True)),
                ('tc_corres_bk_id', models.BigIntegerField(db_column='TC_Corres_BK_ID', null=True, blank=True)),
                ('tc_conta_bk_id', models.BigIntegerField(db_column='TC_Conta_BK_ID', null=True, blank=True)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(db_column='Justificacion', max_length=100, blank=True)),
                ('codigomatch', models.CharField(db_column='CodigoMatch', max_length=20)),
                ('tipo_proceso', models.IntegerField(db_column='Tipo_Proceso', null=True, blank=True)),
            ],
            options={
                'db_table': 'MatchConfirmado_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Matchpropuestos',
            fields=[
                ('idmatch', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idMatch', primary_key=True)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(db_column='Justificacion', max_length=100, blank=True)),
                ('codigomatch', models.CharField(db_column='CodigoMatch', max_length=20)),
                ('puntaje', models.IntegerField(db_column='Puntaje')),
                ('tipo_proceso', models.IntegerField(db_column='Tipo_Proceso', null=True, blank=True)),
            ],
            options={
                'db_table': 'MatchPropuestos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MatchpropuestosBk',
            fields=[
                ('idmatch', models.BigIntegerField(serialize=False, db_column='idMatch', primary_key=True)),
                ('ta_conta_bk_id', models.BigIntegerField(db_column='TA_Conta_BK_ID', null=True, blank=True)),
                ('ta_corres_bk_id', models.BigIntegerField(db_column='TA_Corres_BK_ID', null=True, blank=True)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(db_column='Justificacion', max_length=100, blank=True)),
                ('codigomatch', models.CharField(db_column='CodigoMatch', max_length=20)),
                ('puntaje', models.IntegerField(db_column='Puntaje')),
                ('tipo_proceso', models.IntegerField(db_column='Tipo_Proceso', null=True, blank=True)),
            ],
            options={
                'db_table': 'MatchPropuestos_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idmoneda', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idMoneda', primary_key=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=3)),
                ('nombre', models.CharField(db_column='Nombre', max_length=10)),
                ('cambio_usd', models.FloatField(db_column='Cambio_USD')),
            ],
            options={
                'db_table': 'Moneda',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Mt95',
            fields=[
                ('idmt95', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idMT95', primary_key=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=20)),
                ('ref_relacion', models.CharField(db_column='Ref_Relacion', max_length=20)),
                ('query', models.CharField(db_column='Query', max_length=45)),
                ('narrativa', models.CharField(db_column='Narrativa', max_length=100)),
                ('num_mt', models.BigIntegerField(db_column='Num_MT', null=True, blank=True)),
                ('fecha_msg_original', models.DateTimeField(db_column='Fecha_Msg_Original', null=True, blank=True)),
                ('num_sesion', models.BigIntegerField(db_column='Num_Sesion', null=True, blank=True)),
                ('isn', models.BigIntegerField(db_column='ISN', null=True, blank=True)),
                ('opcion', models.BigIntegerField(db_column='Opcion', null=True, blank=True)),
                ('campo79', models.TextField(db_column='Campo79', blank=True)),
                ('codigo95_idcodigo95', models.ForeignKey(null=True, to='Matcher.Codigo95', blank=True, db_column='Codigo95_idCodigo95')),
            ],
            options={
                'db_table': 'MT95',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Mt95Bk',
            fields=[
                ('idmt95', models.BigIntegerField(serialize=False, db_column='idMT95', primary_key=True)),
                ('ta_corres_bk_id', models.BigIntegerField(db_column='TA_Corres_BK_ID', null=True, blank=True)),
                ('ta_conta_bk_id', models.BigIntegerField(db_column='TA_Conta_BK_ID', null=True, blank=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=20)),
                ('codigo95_bk_idcodigo95', models.BigIntegerField(db_column='Codigo95_BK_idCodigo95', null=True, blank=True)),
                ('ref_relacion', models.CharField(db_column='Ref_Relacion', max_length=20)),
                ('query', models.CharField(db_column='Query', max_length=45)),
                ('narrativa', models.CharField(db_column='Narrativa', max_length=100)),
                ('num_mt', models.BigIntegerField(db_column='Num_MT', null=True, blank=True)),
                ('fecha_msg_original', models.DateTimeField(db_column='Fecha_Msg_Original', null=True, blank=True)),
                ('num_sesion', models.BigIntegerField(db_column='Num_Sesion', null=True, blank=True)),
                ('isn', models.BigIntegerField(db_column='ISN', null=True, blank=True)),
                ('opcion', models.BigIntegerField(db_column='Opcion', null=True, blank=True)),
                ('campo79', models.TextField(db_column='Campo79', blank=True)),
            ],
            options={
                'db_table': 'MT95_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Mt96',
            fields=[
                ('idmt96', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='IdMT96', primary_key=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=20)),
                ('ref_relacion', models.CharField(db_column='Ref_Relacion', max_length=20)),
                ('answer', models.CharField(db_column='Answer', max_length=45)),
                ('narrativa', models.CharField(db_column='Narrativa', max_length=100)),
                ('num_mt', models.BigIntegerField(db_column='Num_MT', null=True, blank=True)),
                ('fecha_msg_original', models.DateTimeField(db_column='Fecha_Msg_Original', null=True, blank=True)),
                ('num_sesion', models.BigIntegerField(db_column='Num_Sesion', null=True, blank=True)),
                ('isn', models.BigIntegerField(db_column='ISN', null=True, blank=True)),
                ('opcion', models.BigIntegerField(db_column='Opcion', null=True, blank=True)),
                ('campo79', models.TextField(db_column='Campo79', blank=True)),
                ('codigo96_idcodigo96', models.ForeignKey(null=True, to='Matcher.Codigo96', blank=True, db_column='Codigo96_idCodigo96')),
                ('mt95_idmt95', models.ForeignKey(null=True, to='Matcher.Mt95', blank=True, db_column='MT95_idMT95')),
            ],
            options={
                'db_table': 'MT96',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Mt99',
            fields=[
                ('idmt99', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idMT99', primary_key=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=20)),
                ('ref_relacion', models.CharField(db_column='Ref_Relacion', max_length=20)),
                ('narrativa', models.CharField(db_column='Narrativa', max_length=45)),
                ('bic', models.CharField(db_column='BIC', max_length=10)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('tipo_mt', models.IntegerField(db_column='Tipo_MT')),
                ('origen', models.IntegerField(db_column='Origen', null=True, blank=True)),
            ],
            options={
                'db_table': 'MT99',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BancoCorresponsalMt99',
            fields=[
                ('banco_corresponsal_idbanco', models.ForeignKey(primary_key=True, to='Matcher.BancoCorresponsal', db_column='Banco_Corresponsal_idBanco')),
                ('mt99_idmt99', models.ForeignKey(serialize=False, primary_key=True, to='Matcher.Mt99', db_column='MT99_idMT99')),
            ],
            options={
                'db_table': 'Banco_Corresponsal_MT99',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Observacioncontabilidad',
            fields=[
                ('idobservacion', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idObservacion', primary_key=True)),
                ('observacion', models.TextField(db_column='Observacion')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'ObservacionContabilidad',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ObservacioncontabilidadBk',
            fields=[
                ('idobservacion', models.BigIntegerField(serialize=False, db_column='idObservacion', primary_key=True)),
                ('ta_conta_bk_id', models.BigIntegerField(db_column='TA_Conta_BK_ID')),
                ('observacion', models.TextField(db_column='Observacion')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'ObservacionContabilidad_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Observacioncorresponsal',
            fields=[
                ('idobservacion', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idObservacion', primary_key=True)),
                ('observacion', models.TextField(db_column='Observacion')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'ObservacionCorresponsal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ObservacioncorresponsalBk',
            fields=[
                ('idobservacion', models.BigIntegerField(serialize=False, db_column='idObservacion', primary_key=True)),
                ('ta_corres_bk_id', models.BigIntegerField(db_column='TA_Corres_BK_ID')),
                ('observacion', models.TextField(db_column='Observacion')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'ObservacionCorresponsal_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('idopcion', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idOpcion', primary_key=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('funprincipal', models.BigIntegerField(db_column='FunPrincipal')),
            ],
            options={
                'db_table': 'Opcion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idperfil', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idPerfil', primary_key=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
            ],
            options={
                'db_table': 'Perfil',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PerfilOpcion',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('opcion_idopcion', models.ForeignKey(db_column='Opcion_idOpcion', to='Matcher.Opcion')),
            ],
            options={
                'db_table': 'Perfil_Opcion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Procesado',
            fields=[
                ('estado_cuenta_idedocuenta', models.ForeignKey(serialize=False, primary_key=True, to='Matcher.EstadoCuenta', db_column='Estado_Cuenta_idEdoCuenta')),
            ],
            options={
                'db_table': 'Procesado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProcesadoBk',
            fields=[
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(serialize=False, primary_key=True, to='Matcher.EstadoCuentaBk', db_column='Estado_Cuenta_BK_idEdoCuenta')),
            ],
            options={
                'db_table': 'Procesado_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReglaTransformacion',
            fields=[
                ('idregla_trans', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idRegla_Trans', primary_key=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('transaccion_corresponsal', models.CharField(db_column='Transaccion_Corresponsal', max_length=20, blank=True)),
                ('ref_corresponsal', models.CharField(db_column='Ref_Corresponsal', max_length=20, blank=True)),
                ('mascara_corresponsal', models.CharField(db_column='Mascara_Corresponsal', max_length=20, blank=True)),
                ('transaccion_contabilidad', models.CharField(db_column='Transaccion_Contabilidad', max_length=20, blank=True)),
                ('ref_contabilidad', models.CharField(db_column='Ref_Contabilidad', max_length=20, blank=True)),
                ('mascara_contabilidad', models.CharField(db_column='Mascara_Contabilidad', max_length=20, blank=True)),
                ('tipo', models.IntegerField(db_column='Tipo', null=True, blank=True)),
            ],
            options={
                'db_table': 'Regla_Transformacion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReglaTransformacionBk',
            fields=[
                ('idregla_trans', models.BigIntegerField(serialize=False, db_column='idRegla_Trans', primary_key=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('transaccion_corresponsal', models.CharField(db_column='Transaccion_Corresponsal', max_length=20, blank=True)),
                ('ref_corresponsal', models.CharField(db_column='Ref_Corresponsal', max_length=20, blank=True)),
                ('mascara_corresponsal', models.CharField(db_column='Mascara_Corresponsal', max_length=20, blank=True)),
                ('transaccion_contabilidad', models.CharField(db_column='Transaccion_Contabilidad', max_length=20, blank=True)),
                ('ref_contabilidad', models.CharField(db_column='Ref_Contabilidad', max_length=20, blank=True)),
                ('mascara_contabilidad', models.CharField(db_column='Mascara_Contabilidad', max_length=20, blank=True)),
                ('tipo', models.IntegerField(db_column='Tipo', null=True, blank=True)),
            ],
            options={
                'db_table': 'Regla_Transformacion_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReversocerradaContabilidad',
            fields=[
                ('idreverso', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idReverso', primary_key=True)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(db_column='Justificacion', max_length=100, blank=True)),
                ('codigomatch', models.CharField(db_column='CodigoMatch', max_length=20, blank=True)),
            ],
            options={
                'db_table': 'ReversoCerrada_Contabilidad',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReversocerradaContabilidadBk',
            fields=[
                ('idreverso', models.BigIntegerField(serialize=False, db_column='idReverso', primary_key=True)),
                ('tc_conta_bk_id', models.BigIntegerField(db_column='TC_Conta_BK_ID')),
                ('tc_conta_bk_id_2', models.BigIntegerField(db_column='TC_Conta_BK_ID_2')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(db_column='Justificacion', max_length=100, blank=True)),
                ('codigomatch', models.CharField(db_column='CodigoMatch', max_length=20, blank=True)),
            ],
            options={
                'db_table': 'ReversoCerrada_Contabilidad_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReversocerradaCorresponsal',
            fields=[
                ('idreverso', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idRevero', primary_key=True)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(db_column='Justificacion', max_length=100, blank=True)),
                ('codigomatch', models.CharField(db_column='CodigoMatch', max_length=20, blank=True)),
            ],
            options={
                'db_table': 'ReversoCerrada_Corresponsal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReversocerradaCorresponsalBk',
            fields=[
                ('idreverso', models.BigIntegerField(serialize=False, db_column='idRevero', primary_key=True)),
                ('tc_corres_bk_id', models.BigIntegerField(db_column='TC_Corres_BK_ID')),
                ('tc_corres_bk_id_2', models.BigIntegerField(db_column='TC_Corres_BK_ID_2')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(db_column='Justificacion', max_length=100, blank=True)),
                ('codigomatch', models.CharField(db_column='CodigoMatch', max_length=20, blank=True)),
            ],
            options={
                'db_table': 'ReversoCerrada_Corresponsal_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('idsesion', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idSesion', primary_key=True)),
                ('login', models.CharField(db_column='Login', max_length=20)),
                ('pass_field', models.CharField(db_column='Pass', max_length=35, blank=True)),
                ('estado', models.CharField(db_column='Estado', max_length=10)),
                ('salt', models.CharField(db_column='Salt', max_length=35, blank=True)),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('conexion', models.CharField(db_column='Conexion', max_length=10, blank=True)),
                ('ldap', models.CharField(db_column='LDAP', max_length=1)),
            ],
            options={
                'db_table': 'Sesion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TransabiertaContabilidad',
            fields=[
                ('idtransaccion', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idTransaccion', primary_key=True)),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina', null=True, blank=True)),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=34, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
                ('idbk', models.BigIntegerField(db_column='idBK', null=True, blank=True)),
                ('estado_cuenta_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_idEdoCuenta', to='Matcher.EstadoCuenta')),
            ],
            options={
                'db_table': 'TransAbierta_Contabilidad',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TransabiertaContabilidadBk',
            fields=[
                ('idtransaccion', models.BigIntegerField(serialize=False, db_column='idTransaccion', primary_key=True)),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina', null=True, blank=True)),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
                ('idbk', models.BigIntegerField(db_column='idBK', null=True, blank=True)),
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_BK_idEdoCuenta', to='Matcher.EstadoCuentaBk')),
            ],
            options={
                'db_table': 'TransAbierta_Contabilidad_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TransabiertaCorresponsal',
            fields=[
                ('idtransaccion', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idTransaccion', primary_key=True)),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina', null=True, blank=True)),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=34, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
                ('idbk', models.BigIntegerField(db_column='idBK', null=True, blank=True)),
                ('estado_cuenta_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_idEdoCuenta', to='Matcher.EstadoCuenta')),
            ],
            options={
                'db_table': 'TransAbierta_Corresponsal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TransabiertaCorresponsalBk',
            fields=[
                ('idtransaccion', models.BigIntegerField(serialize=False, db_column='idTransaccion', primary_key=True)),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina', null=True, blank=True)),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
                ('idbk', models.BigIntegerField(db_column='idBK', null=True, blank=True)),
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_BK_idEdoCuenta', to='Matcher.EstadoCuentaBk')),
            ],
            options={
                'db_table': 'TransAbierta_Corresponsal_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TranscerradaContabilidad',
            fields=[
                ('idtransaccion', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idTransaccion', primary_key=True)),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina', null=True, blank=True)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=34, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
                ('idbk', models.BigIntegerField(db_column='idBK', null=True, blank=True)),
                ('estado_cuenta_idedocuenta', models.ForeignKey(null=True, to='Matcher.EstadoCuenta', blank=True, db_column='Estado_Cuenta_idEdoCuenta')),
            ],
            options={
                'db_table': 'TransCerrada_Contabilidad',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TranscerradaContabilidadBk',
            fields=[
                ('idtransaccion', models.BigIntegerField(serialize=False, db_column='idTransaccion', primary_key=True)),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina', null=True, blank=True)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
                ('idbk', models.BigIntegerField(db_column='idBK', null=True, blank=True)),
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(null=True, to='Matcher.EstadoCuentaBk', blank=True, db_column='Estado_Cuenta_BK_idEdoCuenta')),
            ],
            options={
                'db_table': 'TransCerrada_Contabilidad_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TranscerradaCorresponsal',
            fields=[
                ('idtransaccion', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idTransaccion', primary_key=True)),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina', null=True, blank=True)),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=34, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
                ('idbk', models.BigIntegerField(db_column='idBK', null=True, blank=True)),
                ('estado_cuenta_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_idEdoCuenta', to='Matcher.EstadoCuenta')),
            ],
            options={
                'db_table': 'TransCerrada_Corresponsal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TranscerradaCorresponsalBk',
            fields=[
                ('idtransaccion', models.BigIntegerField(serialize=False, db_column='idTransaccion', primary_key=True)),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina', null=True, blank=True)),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
                ('idbk', models.BigIntegerField(db_column='idBK', null=True, blank=True)),
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_BK_idEdoCuenta', to='Matcher.EstadoCuentaBk')),
            ],
            options={
                'db_table': 'TransCerrada_Corresponsal_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Traza',
            fields=[
                ('idtraza', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idTraza', primary_key=True)),
                ('usuario', models.CharField(db_column='Usuario', max_length=100, blank=True)),
                ('fecha_hora', models.DateTimeField(db_column='Fecha_Hora')),
                ('terminal', models.CharField(db_column='Terminal', max_length=20)),
                ('detalles', models.CharField(db_column='Detalles', max_length=500, blank=True)),
                ('evento_idevento', models.ForeignKey(db_column='Evento_IdEvento', to='Matcher.Evento')),
            ],
            options={
                'db_table': 'Traza',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', sqlserver_ado.fields.BigAutoField(serialize=False, db_column='idUsuario', primary_key=True)),
                ('ci', models.CharField(db_column='CI', max_length=20)),
                ('nombres', models.CharField(db_column='Nombres', max_length=20)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=20)),
                ('direccion', models.CharField(db_column='Direccion', max_length=100)),
                ('telefono', models.CharField(db_column='Telefono', max_length=20)),
                ('mail', models.CharField(db_column='Mail', max_length=35, blank=True)),
                ('observaciones', models.CharField(db_column='Observaciones', max_length=100, blank=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UsuarioCuenta',
            fields=[
                ('usuario_idusuario', models.ForeignKey(serialize=False, primary_key=True, to='Matcher.Usuario', db_column='Usuario_idUsuario')),
                ('cuenta_idcuenta', models.ForeignKey(primary_key=True, to='Matcher.Cuenta', db_column='Cuenta_idCuenta')),
            ],
            options={
                'db_table': 'Usuario_Cuenta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UsuarioCuentaBk',
            fields=[
                ('usuario_bk_idusuario', models.BigIntegerField(db_column='Usuario_BK_idUsuario', primary_key=True)),
                ('cuenta_bk_idcuenta', models.ForeignKey(serialize=False, primary_key=True, to='Matcher.CuentaBk', db_column='Cuenta_BK_idCuenta')),
            ],
            options={
                'db_table': 'Usuario_Cuenta_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VAbiertasconta',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('codigo', models.CharField(db_column='Codigo', max_length=35)),
                ('origen', models.CharField(db_column='Origen', max_length=1)),
                ('pag_edo', models.BigIntegerField(db_column='Pag_Edo')),
                ('idtransaccion', models.BigIntegerField(db_column='idTransaccion')),
                ('estado_cuenta_idedocuenta', models.BigIntegerField(db_column='Estado_Cuenta_idEdoCuenta')),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina', null=True, blank=True)),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=34, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
            ],
            options={
                'db_table': 'v_AbiertasConta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VAbiertascorres',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('idtransaccion', models.BigIntegerField(db_column='idTransaccion')),
                ('estado_cuenta_idedocuenta', models.BigIntegerField(db_column='Estado_Cuenta_idEdoCuenta')),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina', null=True, blank=True)),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=34, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('campo86_940', models.CharField(db_column='Campo86_940', max_length=390, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=35)),
                ('origen', models.CharField(db_column='Origen', max_length=1)),
                ('pag_edo', models.BigIntegerField(db_column='Pag_Edo')),
            ],
            options={
                'db_table': 'v_AbiertasCorres',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VCerradasconta',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('codigo', models.CharField(db_column='Codigo', max_length=35)),
                ('origen', models.CharField(db_column='Origen', max_length=1)),
                ('pagina', models.BigIntegerField(db_column='Pagina')),
                ('idtransaccion', models.BigIntegerField(db_column='idTransaccion')),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('estado_cuenta_idedocuenta', models.BigIntegerField(db_column='Estado_Cuenta_idEdoCuenta', null=True, blank=True)),
                ('expr1', models.IntegerField(db_column='EXPR1', null=True, blank=True)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=34, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
            ],
            options={
                'db_table': 'v_CerradasConta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VCerradascorres',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('codigo', models.CharField(db_column='Codigo', max_length=35)),
                ('origen', models.CharField(db_column='Origen', max_length=1)),
                ('pagina', models.BigIntegerField(db_column='Pagina')),
                ('idtransaccion', models.BigIntegerField(db_column='idTransaccion')),
                ('estado_cuenta_idedocuenta', models.BigIntegerField(db_column='Estado_Cuenta_idEdoCuenta')),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('expr1', models.IntegerField(db_column='EXPR1', null=True, blank=True)),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=34, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('referencianostro', models.CharField(db_column='ReferenciaNostro', max_length=16, blank=True)),
                ('referenciacorresponsal', models.CharField(db_column='ReferenciaCorresponsal', max_length=16, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(db_column='Seguimiento', blank=True)),
            ],
            options={
                'db_table': 'v_CerradasCorres',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VConciliacionconsolidado',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('codigo', models.CharField(db_column='Codigo', max_length=10)),
                ('ref_nostro', models.CharField(db_column='Ref_Nostro', max_length=35)),
                ('ref_vostro', models.CharField(db_column='Ref_Vostro', max_length=35)),
                ('codmoneda', models.CharField(db_column='CodMoneda', max_length=3)),
                ('ultimafechaconciliacion', models.DateTimeField(db_column='UltimaFechaConciliacion', null=True, blank=True)),
                ('tipo_cta', models.IntegerField(db_column='Tipo_Cta', null=True, blank=True)),
                ('idconciliacionconsolidado', models.BigIntegerField(db_column='idConciliacionConsolidado')),
                ('cuenta_idcuenta', models.BigIntegerField(db_column='Cuenta_idCuenta')),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('realizadopor', models.CharField(db_column='RealizadoPor', max_length=60, blank=True)),
            ],
            options={
                'db_table': 'v_ConciliacionConsolidado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VDistincthistoricos',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('refnostro', models.CharField(db_column='RefNostro', max_length=16, blank=True)),
                ('refvostro', models.CharField(db_column='RefVostro', max_length=16, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('origen', models.CharField(db_column='Origen', max_length=1)),
            ],
            options={
                'db_table': 'v_DISTINCTHistoricos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VHistoricos',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('idhistoricoconsolidado', models.BigIntegerField(db_column='idHistoricoConsolidado')),
                ('fechaconciliacion', models.DateTimeField(db_column='FechaConciliacion')),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('autorizadopor', models.CharField(db_column='AutorizadoPor', max_length=60, blank=True)),
                ('firmadopor', models.CharField(db_column='FirmadoPor', max_length=60, blank=True)),
                ('cargofirmante', models.CharField(db_column='CargoFirmante', max_length=60, blank=True)),
                ('realizadopor', models.CharField(db_column='RealizadoPor', max_length=60, blank=True)),
                ('numedo_cont', models.CharField(db_column='NumEdo_Cont', max_length=35, blank=True)),
                ('pag_cont', models.IntegerField(db_column='Pag_Cont', null=True, blank=True)),
                ('fecha_cont', models.DateTimeField(db_column='Fecha_Cont', null=True, blank=True)),
                ('balance_cont', models.FloatField(db_column='Balance_Cont', null=True, blank=True)),
                ('cd_cont', models.CharField(db_column='CD_Cont', max_length=1, blank=True)),
                ('numedo_corr', models.CharField(db_column='NumEdo_Corr', max_length=35, blank=True)),
                ('pag_corr', models.IntegerField(db_column='Pag_Corr', null=True, blank=True)),
                ('fecha_corr', models.DateTimeField(db_column='Fecha_Corr', null=True, blank=True)),
                ('balance_corr', models.FloatField(db_column='Balance_Corr', null=True, blank=True)),
                ('cd_corr', models.CharField(db_column='CD_Corr', max_length=1, blank=True)),
                ('tasa_cambio', models.FloatField(db_column='Tasa_Cambio', null=True, blank=True)),
                ('idhistoricotransacciones', models.BigIntegerField(db_column='idHistoricoTransacciones')),
                ('historicoconsolidado_id', models.BigIntegerField(db_column='HistoricoConsolidado_ID')),
                ('codigo_transaccion', models.CharField(db_column='Codigo_Transaccion', max_length=4)),
                ('pagina', models.IntegerField(db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(db_column='Credito_Debito', max_length=2)),
                ('refvostro', models.CharField(db_column='RefVostro', max_length=16, blank=True)),
                ('refnostro', models.CharField(db_column='RefNostro', max_length=16, blank=True)),
                ('codigocuenta', models.CharField(db_column='CodigoCuenta', max_length=10)),
                ('origen', models.CharField(db_column='Origen', max_length=1)),
                ('observacion', models.CharField(db_column='Observacion', max_length=300, blank=True)),
                ('num_transaccion', models.IntegerField(db_column='Num_Transaccion')),
                ('fecha_salida', models.DateTimeField(db_column='Fecha_Salida', null=True, blank=True)),
                ('numedo', models.CharField(db_column='NumEdo', max_length=35, blank=True)),
            ],
            options={
                'db_table': 'v_Historicos',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa_id_empresa',
            field=models.ForeignKey(related_name='Empresa_id', null=True, to='Matcher.Empresa', blank=True, db_column='Empresa_Id_Empresa'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil_idperfil',
            field=models.ForeignKey(null=True, to='Matcher.Perfil', blank=True, db_column='Perfil_idPerfil'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sesion',
            name='usuario_idusuario',
            field=models.ForeignKey(null=True, to='Matcher.Usuario', blank=True, db_column='Usuario_idUsuario'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reversocerradacorresponsal',
            name='tc_corres',
            field=models.ForeignKey(related_name='TC_Corres_ID', to='Matcher.TranscerradaCorresponsal', db_column='TC_Corres_ID'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reversocerradacorresponsal',
            name='tc_corres_id_2',
            field=models.ForeignKey(related_name='TC_Corres_ID_2', to='Matcher.TranscerradaCorresponsal', db_column='TC_Corres_ID_2'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reversocerradacontabilidad',
            name='tc_conta',
            field=models.ForeignKey(related_name='TC_Conta_ID', to='Matcher.TranscerradaContabilidad', db_column='TC_Conta_ID'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reversocerradacontabilidad',
            name='tc_conta_id_2',
            field=models.ForeignKey(related_name='TC_Conta_ID_2', to='Matcher.TranscerradaContabilidad', db_column='TC_Conta_ID_2'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reglatransformacionbk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_BK_idCuenta', to='Matcher.CuentaBk'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reglatransformacion',
            name='cuenta_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_idCuenta', to='Matcher.Cuenta'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='observacioncorresponsal',
            name='ta_corres',
            field=models.ForeignKey(db_column='TA_Corres_ID', to='Matcher.TransabiertaCorresponsal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='observacioncontabilidad',
            name='ta_conta',
            field=models.ForeignKey(db_column='TA_Conta_ID', to='Matcher.TransabiertaContabilidad'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mt95',
            name='ta_conta',
            field=models.ForeignKey(null=True, to='Matcher.TransabiertaContabilidad', blank=True, db_column='TA_Conta_ID'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mt95',
            name='ta_corres',
            field=models.ForeignKey(null=True, to='Matcher.TransabiertaCorresponsal', blank=True, db_column='TA_Corres_ID'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='matchpropuestos',
            name='ta_conta',
            field=models.ForeignKey(null=True, to='Matcher.TransabiertaContabilidad', blank=True, db_column='TA_Conta_ID'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='matchpropuestos',
            name='ta_corres',
            field=models.ForeignKey(null=True, to='Matcher.TransabiertaCorresponsal', blank=True, db_column='TA_Corres_ID'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='matchconfirmado',
            name='tc_conta',
            field=models.ForeignKey(null=True, to='Matcher.TranscerradaContabilidad', blank=True, db_column='TC_Conta_ID'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='matchconfirmado',
            name='tc_corres',
            field=models.ForeignKey(null=True, to='Matcher.TranscerradaCorresponsal', blank=True, db_column='TC_Corres_ID'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='formatoarchivobk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_BK_idCuenta', to='Matcher.CuentaBk'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='formatoarchivo',
            name='cuenta_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_idCuenta', to='Matcher.Cuenta'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='estadocuentabk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(null=True, to='Matcher.CuentaBk', blank=True, db_column='Cuenta_BK_idCuenta'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='cuenta_idcuenta',
            field=models.ForeignKey(null=True, to='Matcher.Cuenta', blank=True, db_column='Cuenta_idCuenta'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='encajelegalbk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_BK_idCuenta', to='Matcher.CuentaBk'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='encajelegal',
            name='cuenta_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_idCuenta', to='Matcher.Cuenta'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='banco_corresponsal_idbanco',
            field=models.ForeignKey(db_column='Banco_Corresponsal_idBanco', to='Matcher.BancoCorresponsal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='criterios_match_idcriterio',
            field=models.ForeignKey(db_column='Criterios_Match_idCriterio', to='Matcher.CriteriosMatch'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='moneda_idmoneda',
            field=models.ForeignKey(null=True, to='Matcher.Moneda', blank=True, db_column='Moneda_idMoneda'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='conciliacionconsolidadobk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_BK_idCuenta', to='Matcher.CuentaBk'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='conciliacionconsolidado',
            name='cuenta_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_idCuenta', to='Matcher.Cuenta'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alertascuentabk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_BK_idCuenta', to='Matcher.CuentaBk'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alertascuenta',
            name='cuenta_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_idCuenta', to='Matcher.Cuenta'),
            preserve_default=True,
        ),
    ]
