# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import sqlserver_ado.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('idalertas', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idAlertas', serialize=False)),
                ('tipo', models.CharField(max_length=60, db_column='Tipo', blank=True)),
            ],
            options={
                'db_table': 'Alertas',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AlertasCuenta',
            fields=[
                ('idalertascuenta', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idAlertasCuenta', serialize=False)),
                ('valor', models.BigIntegerField(db_column='Valor')),
                ('alertas_idalertas', models.ForeignKey(db_column='Alertas_idAlertas', to='Matcher.Alertas')),
            ],
            options={
                'db_table': 'Alertas_Cuenta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AlertasCuentaBk',
            fields=[
                ('idalertascuenta', models.BigIntegerField(primary_key=True, db_column='idAlertasCuenta', serialize=False)),
                ('alertas_bk_idalertas', models.BigIntegerField(db_column='Alertas_BK_idAlertas')),
                ('valor', models.BigIntegerField(db_column='Valor')),
            ],
            options={
                'db_table': 'Alertas_Cuenta_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BancoCorresponsal',
            fields=[
                ('idbanco', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idBanco', serialize=False)),
                ('codigo', models.CharField(max_length=10, db_column='Codigo')),
                ('nombre', models.CharField(max_length=45, db_column='Nombre')),
            ],
            options={
                'db_table': 'Banco_Corresponsal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Codigo95',
            fields=[
                ('idcodigo95', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idCodigo95', serialize=False)),
                ('codigo', models.BigIntegerField(null=True, blank=True, db_column='Codigo')),
                ('help', models.TextField(db_column='Help')),
            ],
            options={
                'db_table': 'Codigo95',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Codigo96',
            fields=[
                ('idcodigo96', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idCodigo96', serialize=False)),
                ('codigo', models.BigIntegerField(db_column='Codigo')),
                ('help', models.TextField(db_column='Help')),
            ],
            options={
                'db_table': 'Codigo96',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Conciliacionconsolidado',
            fields=[
                ('idconciliacionconsolidado', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idConciliacionConsolidado', serialize=False)),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('realizadopor', models.CharField(max_length=60, db_column='RealizadoPor', blank=True)),
            ],
            options={
                'db_table': 'ConciliacionConsolidado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ConciliacionconsolidadoBk',
            fields=[
                ('idconciliacionconsolidado', models.BigIntegerField(primary_key=True, db_column='idConciliacionConsolidado', serialize=False)),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('realizadopor', models.CharField(max_length=60, db_column='RealizadoPor', blank=True)),
            ],
            options={
                'db_table': 'ConciliacionConsolidado_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('idconfiguracion', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idConfiguracion', serialize=False)),
                ('idioma', models.IntegerField(db_column='Idioma')),
                ('archcontabilidadcarg', models.CharField(max_length=200, db_column='ArchContabilidadCarg')),
                ('archcontabilidadproc', models.CharField(max_length=200, db_column='ArchContabilidadProc')),
                ('archswiftcarg', models.CharField(max_length=200, db_column='ArchSwiftCarg')),
                ('archswiftproc', models.CharField(max_length=200, db_column='ArchSwiftProc')),
                ('bdhost', models.CharField(max_length=200, db_column='BDHost')),
                ('bddriver', models.CharField(max_length=200, db_column='BDDriver')),
                ('bdnombre', models.CharField(max_length=50, db_column='BDNombre')),
                ('bdpuerto', models.IntegerField(db_column='BDPuerto')),
                ('bdusuario', models.CharField(max_length=50, db_column='BDUsuario')),
                ('bdpass', models.CharField(max_length=50, db_column='BDPass')),
                ('alertasservidor', models.CharField(max_length=200, db_column='AlertasServidor', blank=True)),
                ('alertaspuerto', models.IntegerField(null=True, blank=True, db_column='AlertasPuerto')),
                ('alertasusuario', models.CharField(max_length=50, db_column='AlertasUsuario', blank=True)),
                ('alertaspass', models.CharField(max_length=50, db_column='AlertasPass', blank=True)),
                ('tiemporetentrazas', models.IntegerField(null=True, blank=True, db_column='TiempoRetenTrazas')),
                ('matcherhost', models.CharField(max_length=200, db_column='MatcherHost', blank=True)),
                ('matcherpuerto', models.IntegerField(null=True, blank=True, db_column='MatcherPuerto')),
                ('caducidad', models.IntegerField(null=True, blank=True, db_column='Caducidad')),
                ('longitud_minima', models.IntegerField(null=True, blank=True, db_column='Longitud_Minima')),
                ('num_intentos', models.IntegerField(null=True, blank=True, db_column='Num_Intentos')),
                ('num_passrecordar', models.IntegerField(null=True, blank=True, db_column='Num_PassRecordar')),
                ('caracteresespeciales', models.IntegerField(null=True, blank=True, db_column='CaracteresEspeciales')),
                ('numeros', models.IntegerField(null=True, blank=True, db_column='Numeros')),
                ('mayusculas', models.IntegerField(null=True, blank=True, db_column='Mayusculas')),
                ('alfabeticos', models.IntegerField(null=True, blank=True, db_column='Alfabeticos')),
                ('dirarchive', models.CharField(max_length=200, db_column='DirArchive', blank=True)),
                ('dirsalida95', models.CharField(max_length=200, db_column='DirSalida95', blank=True)),
                ('dircarga96', models.CharField(max_length=200, db_column='DirCarga96', blank=True)),
                ('dircarga99', models.CharField(max_length=200, db_column='DirCarga99', blank=True)),
                ('dirsalida99', models.CharField(max_length=200, db_column='DirSalida99', blank=True)),
                ('bic', models.CharField(max_length=200, db_column='Bic', blank=True)),
                ('ldap_ip', models.CharField(max_length=20, db_column='LDAP_IP', blank=True)),
                ('ldap_puerto', models.CharField(max_length=15, db_column='LDAP_Puerto', blank=True)),
                ('ldap_dominio', models.CharField(max_length=50, db_column='LDAP_Dominio', blank=True)),
            ],
            options={
                'db_table': 'Configuracion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CriteriosMatch',
            fields=[
                ('idcriterio', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idCriterio', serialize=False)),
                ('nombre', models.CharField(max_length=20, db_column='Nombre')),
                ('num_entradas', models.BigIntegerField(db_column='Num_Entradas')),
                ('monto1', models.FloatField(null=True, blank=True, db_column='Monto1')),
                ('monto2', models.FloatField(null=True, blank=True, db_column='Monto2')),
                ('monto3', models.FloatField(null=True, blank=True, db_column='Monto3')),
                ('fecha1', models.IntegerField(null=True, blank=True, db_column='Fecha1')),
                ('fecha2', models.IntegerField(null=True, blank=True, db_column='Fecha2')),
                ('fecha3', models.IntegerField(null=True, blank=True, db_column='Fecha3')),
                ('fecha4', models.IntegerField(null=True, blank=True, db_column='Fecha4')),
                ('fecha5', models.IntegerField(null=True, blank=True, db_column='Fecha5')),
            ],
            options={
                'db_table': 'Criterios_Match',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idcuenta', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idCuenta', serialize=False)),
                ('codigo', models.CharField(max_length=10, db_column='Codigo')),
                ('ref_nostro', models.CharField(max_length=35, db_column='Ref_Nostro')),
                ('ref_vostro', models.CharField(max_length=35, db_column='Ref_Vostro')),
                ('descripcion', models.CharField(max_length=45, db_column='Descripcion', blank=True)),
                ('estado', models.CharField(max_length=10, db_column='Estado')),
                ('tiempo_retension', models.IntegerField(db_column='Tiempo_Retension')),
                ('num_saltos', models.IntegerField(db_column='Num_Saltos')),
                ('transaccion_giro', models.CharField(max_length=20, db_column='Transaccion_Giro', blank=True)),
                ('intraday', models.CharField(max_length=1, db_column='Intraday', blank=True)),
                ('correo_alertas', models.CharField(max_length=45, db_column='Correo_Alertas', blank=True)),
                ('montoencajeactual', models.FloatField(null=True, blank=True, db_column='MontoEncajeActual')),
                ('fechaencajeactual', models.DateTimeField(null=True, blank=True, db_column='FechaEncajeActual')),
                ('ultimafechaconciliacion', models.DateTimeField(null=True, blank=True, db_column='UltimaFechaConciliacion')),
                ('ultimoedocuentacargs', models.BigIntegerField(null=True, blank=True, db_column='UltimoEdoCuentaCargS')),
                ('ultimoedocuentaprocs', models.BigIntegerField(null=True, blank=True, db_column='UltimoEdoCuentaProcS')),
                ('ultimoedocuentacargc', models.BigIntegerField(null=True, blank=True, db_column='UltimoEdoCuentaCargC')),
                ('ultimoedocuentaprocc', models.BigIntegerField(null=True, blank=True, db_column='UltimoEdoCuentaProcC')),
                ('concurrencia', models.IntegerField(null=True, blank=True, db_column='Concurrencia')),
                ('ultimafechahistorico', models.DateTimeField(null=True, blank=True, db_column='UltimaFechaHistorico')),
                ('tipo_cta', models.IntegerField(null=True, blank=True, db_column='Tipo_Cta')),
                ('tipo_cargacont', models.IntegerField(null=True, blank=True, db_column='Tipo_CargaCont')),
                ('tipo_carga_corr', models.IntegerField(null=True, blank=True, db_column='Tipo_Carga_Corr')),
                ('tipo_proceso', models.IntegerField(null=True, blank=True, db_column='Tipo_Proceso')),
                ('zona', models.CharField(max_length=100, db_column='Zona', blank=True)),
            ],
            options={
                'db_table': 'Cuenta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CuentaBk',
            fields=[
                ('idcuenta', models.BigIntegerField(primary_key=True, db_column='idCuenta', serialize=False)),
                ('criterios_match_bk_idcriterio', models.BigIntegerField(db_column='Criterios_Match_BK_idCriterio')),
                ('banco_corresponsal_bk_idbanco', models.BigIntegerField(db_column='Banco_Corresponsal_BK_idBanco')),
                ('codigo', models.CharField(max_length=10, db_column='Codigo')),
                ('moneda_bk_idmoneda', models.BigIntegerField(null=True, blank=True, db_column='Moneda_BK_idMoneda')),
                ('ref_nostro', models.CharField(max_length=35, db_column='Ref_Nostro')),
                ('ref_vostro', models.CharField(max_length=35, db_column='Ref_Vostro')),
                ('descripcion', models.CharField(max_length=45, db_column='Descripcion', blank=True)),
                ('estado', models.CharField(max_length=10, db_column='Estado')),
                ('tiempo_retension', models.IntegerField(db_column='Tiempo_Retension')),
                ('num_saltos', models.IntegerField(db_column='Num_Saltos')),
                ('transaccion_giro', models.CharField(max_length=20, db_column='Transaccion_Giro', blank=True)),
                ('intraday', models.CharField(max_length=1, db_column='Intraday', blank=True)),
                ('correo_alertas', models.CharField(max_length=45, db_column='Correo_Alertas', blank=True)),
                ('montoencajeactual', models.FloatField(null=True, blank=True, db_column='MontoEncajeActual')),
                ('fechaencajeactual', models.DateTimeField(null=True, blank=True, db_column='FechaEncajeActual')),
                ('ultimafechaconciliacion', models.DateTimeField(null=True, blank=True, db_column='UltimaFechaConciliacion')),
                ('ultimoedocuentacargs', models.BigIntegerField(null=True, blank=True, db_column='UltimoEdoCuentaCargS')),
                ('ultimoedocuentaprocs', models.BigIntegerField(null=True, blank=True, db_column='UltimoEdoCuentaProcS')),
                ('ultimoedocuentacargc', models.BigIntegerField(null=True, blank=True, db_column='UltimoEdoCuentaCargC')),
                ('ultimoedocuentaprocc', models.BigIntegerField(null=True, blank=True, db_column='UltimoEdoCuentaProcC')),
                ('concurrencia', models.IntegerField(null=True, blank=True, db_column='Concurrencia')),
                ('ultimafechahistorico', models.DateTimeField(null=True, blank=True, db_column='UltimaFechaHistorico')),
                ('tipo_cta', models.IntegerField(null=True, blank=True, db_column='Tipo_Cta')),
                ('tipo_cargacont', models.IntegerField(null=True, blank=True, db_column='Tipo_CargaCont')),
                ('tipo_carga_corr', models.IntegerField(null=True, blank=True, db_column='Tipo_Carga_Corr')),
                ('tipo_proceso', models.IntegerField(null=True, blank=True, db_column='Tipo_Proceso')),
                ('zona', models.CharField(max_length=100, db_column='Zona', blank=True)),
            ],
            options={
                'db_table': 'Cuenta_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='Id_Empresa', serialize=False)),
                ('nombre', models.CharField(max_length=50, db_column='Nombre')),
                ('dir_logo', models.CharField(max_length=200, db_column='Dir_Logo')),
                ('nombregrupo', models.CharField(max_length=50, db_column='NombreGrupo')),
                ('direccion', models.CharField(max_length=150, db_column='Direccion')),
                ('creditoscontabilidad', models.CharField(max_length=60, db_column='CreditosContabilidad')),
                ('debitoscontabilidad', models.CharField(max_length=60, db_column='DebitosContabilidad')),
                ('creditoscorresponsal', models.CharField(max_length=60, db_column='CreditosCorresponsal')),
                ('debitoscorresponsal', models.CharField(max_length=60, db_column='DebitosCorresponsal')),
                ('pais', models.CharField(max_length=15, db_column='Pais')),
                ('autorizadopor', models.CharField(max_length=60, db_column='AutorizadoPor', blank=True)),
                ('firmadopor', models.CharField(max_length=60, db_column='FirmadoPor', blank=True)),
                ('cargofirmante', models.CharField(max_length=60, db_column='CargoFirmante', blank=True)),
            ],
            options={
                'db_table': 'Empresa',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Encajelegal',
            fields=[
                ('idencajelegal', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idEncajeLegal', serialize=False)),
                ('monto', models.FloatField(db_column='Monto')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'EncajeLegal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EncajelegalBk',
            fields=[
                ('idencajelegal', models.BigIntegerField(primary_key=True, db_column='idEncajeLegal', serialize=False)),
                ('monto', models.FloatField(db_column='Monto')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'EncajeLegal_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('idedocuenta', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idEdoCuenta', serialize=False)),
                ('codigo', models.CharField(max_length=35, db_column='Codigo')),
                ('origen', models.CharField(max_length=1, db_column='Origen')),
                ('pagina', models.BigIntegerField(db_column='Pagina')),
                ('balance_inicial', models.FloatField(db_column='Balance_Inicial')),
                ('balance_final', models.FloatField(db_column='Balance_Final')),
                ('m_finicial', models.CharField(max_length=1, db_column='M_Finicial')),
                ('m_ffinal', models.CharField(max_length=1, db_column='M_Ffinal')),
                ('fecha_inicial', models.DateTimeField(db_column='Fecha_Inicial')),
                ('fecha_final', models.DateTimeField(db_column='Fecha_Final')),
                ('c_dinicial', models.CharField(max_length=1, db_column='C_DInicial')),
                ('c_dfinal', models.CharField(max_length=1, db_column='C_DFinal')),
                ('idbk', models.BigIntegerField(null=True, blank=True, db_column='idBK')),
            ],
            options={
                'db_table': 'Estado_Cuenta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cargado',
            fields=[
                ('estado_cuenta_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_idEdoCuenta', primary_key=True, serialize=False, to='Matcher.EstadoCuenta')),
            ],
            options={
                'db_table': 'Cargado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EstadoCuentaBk',
            fields=[
                ('idedocuenta', models.BigIntegerField(primary_key=True, db_column='idEdoCuenta', serialize=False)),
                ('codigo', models.CharField(max_length=35, db_column='Codigo')),
                ('origen', models.CharField(max_length=1, db_column='Origen')),
                ('pagina', models.BigIntegerField(db_column='Pagina')),
                ('balance_inicial', models.FloatField(db_column='Balance_Inicial')),
                ('balance_final', models.FloatField(db_column='Balance_Final')),
                ('m_finicial', models.CharField(max_length=1, db_column='M_Finicial')),
                ('m_ffinal', models.CharField(max_length=1, db_column='M_Ffinal')),
                ('fecha_inicial', models.DateTimeField(db_column='Fecha_Inicial')),
                ('fecha_final', models.DateTimeField(db_column='Fecha_Final')),
                ('c_dinicial', models.CharField(max_length=1, db_column='C_DInicial')),
                ('c_dfinal', models.CharField(max_length=1, db_column='C_DFinal')),
                ('idbk', models.BigIntegerField(null=True, blank=True, db_column='idBK')),
            ],
            options={
                'db_table': 'Estado_Cuenta_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CargadoBk',
            fields=[
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_BK_idEdoCuenta', primary_key=True, serialize=False, to='Matcher.EstadoCuentaBk')),
            ],
            options={
                'db_table': 'Cargado_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.IntegerField(primary_key=True, db_column='IdEvento', serialize=False)),
                ('accion', models.CharField(max_length=45, db_column='Accion')),
            ],
            options={
                'db_table': 'Evento',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Formatoarchivo',
            fields=[
                ('idformato', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idFormato', serialize=False)),
                ('nombre', models.CharField(max_length=100, db_column='Nombre')),
                ('separador', models.CharField(max_length=2, db_column='Separador')),
                ('tipo', models.CharField(max_length=2, db_column='Tipo')),
                ('formato', models.CharField(max_length=20, db_column='Formato')),
            ],
            options={
                'db_table': 'FormatoArchivo',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FormatoarchivoBk',
            fields=[
                ('idformato', models.BigIntegerField(primary_key=True, db_column='idFormato', serialize=False)),
                ('nombre', models.CharField(max_length=100, db_column='Nombre')),
                ('separador', models.CharField(max_length=2, db_column='Separador')),
                ('tipo', models.CharField(max_length=2, db_column='Tipo')),
                ('formato', models.CharField(max_length=20, db_column='Formato')),
            ],
            options={
                'db_table': 'FormatoArchivo_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Historicoconsolidado',
            fields=[
                ('idhistoricoconsolidado', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idHistoricoConsolidado', serialize=False)),
                ('fechaconciliacion', models.DateTimeField(db_column='FechaConciliacion')),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('autorizadopor', models.CharField(max_length=60, db_column='AutorizadoPor', blank=True)),
                ('firmadopor', models.CharField(max_length=60, db_column='FirmadoPor', blank=True)),
                ('cargofirmante', models.CharField(max_length=60, db_column='CargoFirmante', blank=True)),
                ('realizadopor', models.CharField(max_length=60, db_column='RealizadoPor', blank=True)),
                ('numedo_cont', models.CharField(max_length=35, db_column='NumEdo_Cont', blank=True)),
                ('pag_cont', models.IntegerField(null=True, blank=True, db_column='Pag_Cont')),
                ('fecha_cont', models.DateTimeField(null=True, blank=True, db_column='Fecha_Cont')),
                ('balance_cont', models.FloatField(null=True, blank=True, db_column='Balance_Cont')),
                ('cd_cont', models.CharField(max_length=1, db_column='CD_Cont', blank=True)),
                ('numedo_corr', models.CharField(max_length=35, db_column='NumEdo_Corr', blank=True)),
                ('pag_corr', models.IntegerField(null=True, blank=True, db_column='Pag_Corr')),
                ('fecha_corr', models.DateTimeField(null=True, blank=True, db_column='Fecha_Corr')),
                ('balance_corr', models.FloatField(null=True, blank=True, db_column='Balance_Corr')),
                ('cd_corr', models.CharField(max_length=1, db_column='CD_Corr', blank=True)),
                ('tasa_cambio', models.FloatField(null=True, blank=True, db_column='Tasa_Cambio')),
            ],
            options={
                'db_table': 'HistoricoConsolidado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HistoricoconsolidadoBk',
            fields=[
                ('idhistoricoconsolidado', models.BigIntegerField(primary_key=True, db_column='idHistoricoConsolidado', serialize=False)),
                ('fechaconciliacion', models.DateTimeField(db_column='FechaConciliacion')),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('autorizadopor', models.CharField(max_length=60, db_column='AutorizadoPor', blank=True)),
                ('firmadopor', models.CharField(max_length=60, db_column='FirmadoPor', blank=True)),
                ('cargofirmante', models.CharField(max_length=60, db_column='CargoFirmante', blank=True)),
                ('realizadopor', models.CharField(max_length=60, db_column='RealizadoPor', blank=True)),
                ('numedo_cont', models.CharField(max_length=35, db_column='NumEdo_Cont', blank=True)),
                ('pag_cont', models.IntegerField(null=True, blank=True, db_column='Pag_Cont')),
                ('fecha_cont', models.DateTimeField(null=True, blank=True, db_column='Fecha_Cont')),
                ('balance_cont', models.FloatField(null=True, blank=True, db_column='Balance_Cont')),
                ('cd_cont', models.CharField(max_length=1, db_column='CD_Cont', blank=True)),
                ('numedo_corr', models.CharField(max_length=35, db_column='NumEdo_Corr', blank=True)),
                ('pag_corr', models.IntegerField(null=True, blank=True, db_column='Pag_Corr')),
                ('fecha_corr', models.DateTimeField(null=True, blank=True, db_column='Fecha_Corr')),
                ('balance_corr', models.FloatField(null=True, blank=True, db_column='Balance_Corr')),
                ('cd_corr', models.CharField(max_length=1, db_column='CD_Corr', blank=True)),
                ('tasa_cambio', models.FloatField(null=True, blank=True, db_column='Tasa_Cambio')),
            ],
            options={
                'db_table': 'HistoricoConsolidado_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Historicotransacciones',
            fields=[
                ('idhistoricotransacciones', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idHistoricoTransacciones', serialize=False)),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=45, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('refvostro', models.CharField(max_length=16, db_column='RefVostro', blank=True)),
                ('refnostro', models.CharField(max_length=16, db_column='RefNostro', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('origen', models.CharField(max_length=1, db_column='Origen')),
                ('observacion', models.CharField(max_length=300, db_column='Observacion', blank=True)),
                ('num_transaccion', models.IntegerField(db_column='Num_Transaccion')),
                ('fecha_salida', models.DateTimeField(null=True, blank=True, db_column='Fecha_Salida')),
                ('numedo', models.CharField(max_length=35, db_column='NumEdo', blank=True)),
                ('historicoconsolidado', models.ForeignKey(db_column='HistoricoConsolidado_ID', to='Matcher.Historicoconsolidado')),
            ],
            options={
                'db_table': 'HistoricoTransacciones',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HistoricotransaccionesBk',
            fields=[
                ('idhistoricotransacciones', models.BigIntegerField(primary_key=True, db_column='idHistoricoTransacciones', serialize=False)),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=45, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('refvostro', models.CharField(max_length=16, db_column='RefVostro', blank=True)),
                ('refnostro', models.CharField(max_length=16, db_column='RefNostro', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('origen', models.CharField(max_length=1, db_column='Origen')),
                ('observacion', models.CharField(max_length=300, db_column='Observacion', blank=True)),
                ('num_transaccion', models.IntegerField(db_column='Num_Transaccion')),
                ('fecha_salida', models.DateTimeField(null=True, blank=True, db_column='Fecha_Salida')),
                ('numedo', models.CharField(max_length=35, db_column='NumEdo', blank=True)),
                ('historicoconsolidado_bk', models.ForeignKey(db_column='HistoricoConsolidado_BK_ID', to='Matcher.HistoricoconsolidadoBk')),
            ],
            options={
                'db_table': 'HistoricoTransacciones_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('ididioma', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idIdioma', serialize=False)),
                ('espanol', models.CharField(max_length=200, db_column='Espanol')),
                ('ingles', models.CharField(max_length=200, db_column='Ingles')),
            ],
            options={
                'db_table': 'Idioma',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Matchconfirmado',
            fields=[
                ('idmatch', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idMatch', serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(max_length=100, db_column='Justificacion', blank=True)),
                ('codigomatch', models.CharField(max_length=20, db_column='CodigoMatch')),
                ('tipo_proceso', models.IntegerField(null=True, blank=True, db_column='Tipo_Proceso')),
            ],
            options={
                'db_table': 'MatchConfirmado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MatchconfirmadoBk',
            fields=[
                ('idmatch', models.BigIntegerField(primary_key=True, db_column='idMatch', serialize=False)),
                ('tc_corres_bk_id', models.BigIntegerField(null=True, blank=True, db_column='TC_Corres_BK_ID')),
                ('tc_conta_bk_id', models.BigIntegerField(null=True, blank=True, db_column='TC_Conta_BK_ID')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(max_length=100, db_column='Justificacion', blank=True)),
                ('codigomatch', models.CharField(max_length=20, db_column='CodigoMatch')),
                ('tipo_proceso', models.IntegerField(null=True, blank=True, db_column='Tipo_Proceso')),
            ],
            options={
                'db_table': 'MatchConfirmado_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Matchpropuestos',
            fields=[
                ('idmatch', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idMatch', serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(max_length=100, db_column='Justificacion', blank=True)),
                ('codigomatch', models.CharField(max_length=20, db_column='CodigoMatch')),
                ('puntaje', models.IntegerField(db_column='Puntaje')),
                ('tipo_proceso', models.IntegerField(null=True, blank=True, db_column='Tipo_Proceso')),
            ],
            options={
                'db_table': 'MatchPropuestos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MatchpropuestosBk',
            fields=[
                ('idmatch', models.BigIntegerField(primary_key=True, db_column='idMatch', serialize=False)),
                ('ta_conta_bk_id', models.BigIntegerField(null=True, blank=True, db_column='TA_Conta_BK_ID')),
                ('ta_corres_bk_id', models.BigIntegerField(null=True, blank=True, db_column='TA_Corres_BK_ID')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(max_length=100, db_column='Justificacion', blank=True)),
                ('codigomatch', models.CharField(max_length=20, db_column='CodigoMatch')),
                ('puntaje', models.IntegerField(db_column='Puntaje')),
                ('tipo_proceso', models.IntegerField(null=True, blank=True, db_column='Tipo_Proceso')),
            ],
            options={
                'db_table': 'MatchPropuestos_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idmoneda', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idMoneda', serialize=False)),
                ('codigo', models.CharField(max_length=3, db_column='Codigo')),
                ('nombre', models.CharField(max_length=10, db_column='Nombre')),
                ('cambio_usd', models.FloatField(db_column='Cambio_USD')),
            ],
            options={
                'db_table': 'Moneda',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Mt95',
            fields=[
                ('idmt95', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idMT95', serialize=False)),
                ('codigo', models.CharField(max_length=20, db_column='Codigo')),
                ('ref_relacion', models.CharField(max_length=20, db_column='Ref_Relacion')),
                ('query', models.CharField(max_length=45, db_column='Query')),
                ('narrativa', models.CharField(max_length=100, db_column='Narrativa')),
                ('num_mt', models.BigIntegerField(null=True, blank=True, db_column='Num_MT')),
                ('fecha_msg_original', models.DateTimeField(null=True, blank=True, db_column='Fecha_Msg_Original')),
                ('num_sesion', models.BigIntegerField(null=True, blank=True, db_column='Num_Sesion')),
                ('isn', models.BigIntegerField(null=True, blank=True, db_column='ISN')),
                ('opcion', models.BigIntegerField(null=True, blank=True, db_column='Opcion')),
                ('campo79', models.TextField(blank=True, db_column='Campo79')),
                ('codigo95_idcodigo95', models.ForeignKey(db_column='Codigo95_idCodigo95', null=True, blank=True, to='Matcher.Codigo95')),
            ],
            options={
                'db_table': 'MT95',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Mt95Bk',
            fields=[
                ('idmt95', models.BigIntegerField(primary_key=True, db_column='idMT95', serialize=False)),
                ('ta_corres_bk_id', models.BigIntegerField(null=True, blank=True, db_column='TA_Corres_BK_ID')),
                ('ta_conta_bk_id', models.BigIntegerField(null=True, blank=True, db_column='TA_Conta_BK_ID')),
                ('codigo', models.CharField(max_length=20, db_column='Codigo')),
                ('codigo95_bk_idcodigo95', models.BigIntegerField(null=True, blank=True, db_column='Codigo95_BK_idCodigo95')),
                ('ref_relacion', models.CharField(max_length=20, db_column='Ref_Relacion')),
                ('query', models.CharField(max_length=45, db_column='Query')),
                ('narrativa', models.CharField(max_length=100, db_column='Narrativa')),
                ('num_mt', models.BigIntegerField(null=True, blank=True, db_column='Num_MT')),
                ('fecha_msg_original', models.DateTimeField(null=True, blank=True, db_column='Fecha_Msg_Original')),
                ('num_sesion', models.BigIntegerField(null=True, blank=True, db_column='Num_Sesion')),
                ('isn', models.BigIntegerField(null=True, blank=True, db_column='ISN')),
                ('opcion', models.BigIntegerField(null=True, blank=True, db_column='Opcion')),
                ('campo79', models.TextField(blank=True, db_column='Campo79')),
            ],
            options={
                'db_table': 'MT95_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Mt96',
            fields=[
                ('idmt96', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='IdMT96', serialize=False)),
                ('codigo', models.CharField(max_length=20, db_column='Codigo')),
                ('ref_relacion', models.CharField(max_length=20, db_column='Ref_Relacion')),
                ('answer', models.CharField(max_length=45, db_column='Answer')),
                ('narrativa', models.CharField(max_length=100, db_column='Narrativa')),
                ('num_mt', models.BigIntegerField(null=True, blank=True, db_column='Num_MT')),
                ('fecha_msg_original', models.DateTimeField(null=True, blank=True, db_column='Fecha_Msg_Original')),
                ('num_sesion', models.BigIntegerField(null=True, blank=True, db_column='Num_Sesion')),
                ('isn', models.BigIntegerField(null=True, blank=True, db_column='ISN')),
                ('opcion', models.BigIntegerField(null=True, blank=True, db_column='Opcion')),
                ('campo79', models.TextField(blank=True, db_column='Campo79')),
                ('codigo96_idcodigo96', models.ForeignKey(db_column='Codigo96_idCodigo96', null=True, blank=True, to='Matcher.Codigo96')),
                ('mt95_idmt95', models.ForeignKey(db_column='MT95_idMT95', null=True, blank=True, to='Matcher.Mt95')),
            ],
            options={
                'db_table': 'MT96',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Mt99',
            fields=[
                ('idmt99', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idMT99', serialize=False)),
                ('codigo', models.CharField(max_length=20, db_column='Codigo')),
                ('ref_relacion', models.CharField(max_length=20, db_column='Ref_Relacion')),
                ('narrativa', models.CharField(max_length=45, db_column='Narrativa')),
                ('bic', models.CharField(max_length=10, db_column='BIC')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('tipo_mt', models.IntegerField(db_column='Tipo_MT')),
                ('origen', models.IntegerField(null=True, blank=True, db_column='Origen')),
            ],
            options={
                'db_table': 'MT99',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BancoCorresponsalMt99',
            fields=[
                ('banco_corresponsal_idbanco', models.ForeignKey(db_column='Banco_Corresponsal_idBanco', primary_key=True, serialize=False, to='Matcher.BancoCorresponsal')),
                ('mt99_idmt99', models.ForeignKey(db_column='MT99_idMT99', primary_key=True, to='Matcher.Mt99')),
            ],
            options={
                'db_table': 'Banco_Corresponsal_MT99',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Observacioncontabilidad',
            fields=[
                ('idobservacion', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idObservacion', serialize=False)),
                ('observacion', models.TextField(db_column='Observacion')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'ObservacionContabilidad',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ObservacioncontabilidadBk',
            fields=[
                ('idobservacion', models.BigIntegerField(primary_key=True, db_column='idObservacion', serialize=False)),
                ('ta_conta_bk_id', models.BigIntegerField(db_column='TA_Conta_BK_ID')),
                ('observacion', models.TextField(db_column='Observacion')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'ObservacionContabilidad_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Observacioncorresponsal',
            fields=[
                ('idobservacion', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idObservacion', serialize=False)),
                ('observacion', models.TextField(db_column='Observacion')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'ObservacionCorresponsal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ObservacioncorresponsalBk',
            fields=[
                ('idobservacion', models.BigIntegerField(primary_key=True, db_column='idObservacion', serialize=False)),
                ('ta_corres_bk_id', models.BigIntegerField(db_column='TA_Corres_BK_ID')),
                ('observacion', models.TextField(db_column='Observacion')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'ObservacionCorresponsal_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('idopcion', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idOpcion', serialize=False)),
                ('nombre', models.CharField(max_length=50, db_column='Nombre')),
                ('funprincipal', models.BigIntegerField(db_column='FunPrincipal')),
            ],
            options={
                'db_table': 'Opcion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idperfil', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idPerfil', serialize=False)),
                ('nombre', models.CharField(max_length=20, db_column='Nombre')),
            ],
            options={
                'db_table': 'Perfil',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PerfilOpcion',
            fields=[
                ('opcion_idopcion', models.ForeignKey(db_column='Opcion_idOpcion', primary_key=True, serialize=False, to='Matcher.Opcion')),
                ('perfil_idperfil', models.ForeignKey(db_column='Perfil_idPerfil', to='Matcher.Perfil')),
            ],
            options={
                'db_table': 'Perfil_Opcion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Procesado',
            fields=[
                ('estado_cuenta_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_idEdoCuenta', primary_key=True, serialize=False, to='Matcher.EstadoCuenta')),
            ],
            options={
                'db_table': 'Procesado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProcesadoBk',
            fields=[
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_BK_idEdoCuenta', primary_key=True, serialize=False, to='Matcher.EstadoCuentaBk')),
            ],
            options={
                'db_table': 'Procesado_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReglaTransformacion',
            fields=[
                ('idregla_trans', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idRegla_Trans', serialize=False)),
                ('nombre', models.CharField(max_length=20, db_column='Nombre')),
                ('transaccion_corresponsal', models.CharField(max_length=20, db_column='Transaccion_Corresponsal', blank=True)),
                ('ref_corresponsal', models.CharField(max_length=20, db_column='Ref_Corresponsal', blank=True)),
                ('mascara_corresponsal', models.CharField(max_length=20, db_column='Mascara_Corresponsal', blank=True)),
                ('transaccion_contabilidad', models.CharField(max_length=20, db_column='Transaccion_Contabilidad', blank=True)),
                ('ref_contabilidad', models.CharField(max_length=20, db_column='Ref_Contabilidad', blank=True)),
                ('mascara_contabilidad', models.CharField(max_length=20, db_column='Mascara_Contabilidad', blank=True)),
                ('tipo', models.IntegerField(null=True, blank=True, db_column='Tipo')),
            ],
            options={
                'db_table': 'Regla_Transformacion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReglaTransformacionBk',
            fields=[
                ('idregla_trans', models.BigIntegerField(primary_key=True, db_column='idRegla_Trans', serialize=False)),
                ('nombre', models.CharField(max_length=20, db_column='Nombre')),
                ('transaccion_corresponsal', models.CharField(max_length=20, db_column='Transaccion_Corresponsal', blank=True)),
                ('ref_corresponsal', models.CharField(max_length=20, db_column='Ref_Corresponsal', blank=True)),
                ('mascara_corresponsal', models.CharField(max_length=20, db_column='Mascara_Corresponsal', blank=True)),
                ('transaccion_contabilidad', models.CharField(max_length=20, db_column='Transaccion_Contabilidad', blank=True)),
                ('ref_contabilidad', models.CharField(max_length=20, db_column='Ref_Contabilidad', blank=True)),
                ('mascara_contabilidad', models.CharField(max_length=20, db_column='Mascara_Contabilidad', blank=True)),
                ('tipo', models.IntegerField(null=True, blank=True, db_column='Tipo')),
            ],
            options={
                'db_table': 'Regla_Transformacion_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReversocerradaContabilidad',
            fields=[
                ('idreverso', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idReverso', serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(max_length=100, db_column='Justificacion', blank=True)),
                ('codigomatch', models.CharField(max_length=20, db_column='CodigoMatch', blank=True)),
            ],
            options={
                'db_table': 'ReversoCerrada_Contabilidad',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReversocerradaContabilidadBk',
            fields=[
                ('idreverso', models.BigIntegerField(primary_key=True, db_column='idReverso', serialize=False)),
                ('tc_conta_bk_id', models.BigIntegerField(db_column='TC_Conta_BK_ID')),
                ('tc_conta_bk_id_2', models.BigIntegerField(db_column='TC_Conta_BK_ID_2')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(max_length=100, db_column='Justificacion', blank=True)),
                ('codigomatch', models.CharField(max_length=20, db_column='CodigoMatch', blank=True)),
            ],
            options={
                'db_table': 'ReversoCerrada_Contabilidad_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReversocerradaCorresponsal',
            fields=[
                ('idreverso', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idRevero', serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(max_length=100, db_column='Justificacion', blank=True)),
                ('codigomatch', models.CharField(max_length=20, db_column='CodigoMatch', blank=True)),
            ],
            options={
                'db_table': 'ReversoCerrada_Corresponsal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReversocerradaCorresponsalBk',
            fields=[
                ('idreverso', models.BigIntegerField(primary_key=True, db_column='idRevero', serialize=False)),
                ('tc_corres_bk_id', models.BigIntegerField(db_column='TC_Corres_BK_ID')),
                ('tc_corres_bk_id_2', models.BigIntegerField(db_column='TC_Corres_BK_ID_2')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('auto_manual', models.IntegerField(db_column='Auto_Manual')),
                ('justificacion', models.CharField(max_length=100, db_column='Justificacion', blank=True)),
                ('codigomatch', models.CharField(max_length=20, db_column='CodigoMatch', blank=True)),
            ],
            options={
                'db_table': 'ReversoCerrada_Corresponsal_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('idsesion', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idSesion', serialize=False)),
                ('login', models.CharField(max_length=20, db_column='Login')),
                ('pass_field', models.CharField(max_length=35, db_column='Pass', blank=True)),
                ('estado', models.CharField(max_length=10, db_column='Estado')),
                ('salt', models.CharField(max_length=35, db_column='Salt', blank=True)),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('conexion', models.CharField(max_length=10, db_column='Conexion', blank=True)),
                ('ldap', models.CharField(max_length=1, db_column='LDAP')),
            ],
            options={
                'db_table': 'Sesion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TransabiertaContabilidad',
            fields=[
                ('idtransaccion', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idTransaccion', serialize=False)),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(null=True, blank=True, db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=34, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
                ('idbk', models.BigIntegerField(null=True, blank=True, db_column='idBK')),
                ('estado_cuenta_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_idEdoCuenta', to='Matcher.EstadoCuenta')),
            ],
            options={
                'db_table': 'TransAbierta_Contabilidad',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TransabiertaContabilidadBk',
            fields=[
                ('idtransaccion', models.BigIntegerField(primary_key=True, db_column='idTransaccion', serialize=False)),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(null=True, blank=True, db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=45, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
                ('idbk', models.BigIntegerField(null=True, blank=True, db_column='idBK')),
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_BK_idEdoCuenta', to='Matcher.EstadoCuentaBk')),
            ],
            options={
                'db_table': 'TransAbierta_Contabilidad_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TransabiertaCorresponsal',
            fields=[
                ('idtransaccion', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idTransaccion', serialize=False)),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(null=True, blank=True, db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=34, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
                ('idbk', models.BigIntegerField(null=True, blank=True, db_column='idBK')),
                ('estado_cuenta_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_idEdoCuenta', to='Matcher.EstadoCuenta')),
            ],
            options={
                'db_table': 'TransAbierta_Corresponsal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TransabiertaCorresponsalBk',
            fields=[
                ('idtransaccion', models.BigIntegerField(primary_key=True, db_column='idTransaccion', serialize=False)),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(null=True, blank=True, db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=45, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
                ('idbk', models.BigIntegerField(null=True, blank=True, db_column='idBK')),
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_BK_idEdoCuenta', to='Matcher.EstadoCuentaBk')),
            ],
            options={
                'db_table': 'TransAbierta_Corresponsal_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TranscerradaContabilidad',
            fields=[
                ('idtransaccion', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idTransaccion', serialize=False)),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(null=True, blank=True, db_column='Pagina')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('descripcion', models.CharField(max_length=34, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
                ('idbk', models.BigIntegerField(null=True, blank=True, db_column='idBK')),
                ('estado_cuenta_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_idEdoCuenta', null=True, blank=True, to='Matcher.EstadoCuenta')),
            ],
            options={
                'db_table': 'TransCerrada_Contabilidad',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TranscerradaContabilidadBk',
            fields=[
                ('idtransaccion', models.BigIntegerField(primary_key=True, db_column='idTransaccion', serialize=False)),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(null=True, blank=True, db_column='Pagina')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('descripcion', models.CharField(max_length=45, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
                ('idbk', models.BigIntegerField(null=True, blank=True, db_column='idBK')),
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_BK_idEdoCuenta', null=True, blank=True, to='Matcher.EstadoCuentaBk')),
            ],
            options={
                'db_table': 'TransCerrada_Contabilidad_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TranscerradaCorresponsal',
            fields=[
                ('idtransaccion', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idTransaccion', serialize=False)),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(null=True, blank=True, db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=34, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
                ('idbk', models.BigIntegerField(null=True, blank=True, db_column='idBK')),
                ('estado_cuenta_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_idEdoCuenta', to='Matcher.EstadoCuenta')),
            ],
            options={
                'db_table': 'TransCerrada_Corresponsal',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TranscerradaCorresponsalBk',
            fields=[
                ('idtransaccion', models.BigIntegerField(primary_key=True, db_column='idTransaccion', serialize=False)),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(null=True, blank=True, db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=45, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
                ('idbk', models.BigIntegerField(null=True, blank=True, db_column='idBK')),
                ('estado_cuenta_bk_idedocuenta', models.ForeignKey(db_column='Estado_Cuenta_BK_idEdoCuenta', to='Matcher.EstadoCuentaBk')),
            ],
            options={
                'db_table': 'TransCerrada_Corresponsal_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Traza',
            fields=[
                ('idtraza', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idTraza', serialize=False)),
                ('usuario', models.CharField(max_length=100, db_column='Usuario', blank=True)),
                ('fecha_hora', models.DateTimeField(db_column='Fecha_Hora')),
                ('terminal', models.CharField(max_length=20, db_column='Terminal')),
                ('detalles', models.CharField(max_length=500, db_column='Detalles', blank=True)),
                ('evento_idevento', models.ForeignKey(db_column='Evento_IdEvento', to='Matcher.Evento')),
            ],
            options={
                'db_table': 'Traza',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', sqlserver_ado.fields.BigAutoField(primary_key=True, db_column='idUsuario', serialize=False)),
                ('ci', models.CharField(max_length=20, db_column='CI')),
                ('nombres', models.CharField(max_length=20, db_column='Nombres')),
                ('apellidos', models.CharField(max_length=20, db_column='Apellidos')),
                ('direccion', models.CharField(max_length=100, db_column='Direccion')),
                ('telefono', models.CharField(max_length=20, db_column='Telefono')),
                ('mail', models.CharField(max_length=35, db_column='Mail', blank=True)),
                ('observaciones', models.CharField(max_length=100, db_column='Observaciones', blank=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UsuarioCuenta',
            fields=[
                ('usuario_idusuario', models.ForeignKey(db_column='Usuario_idUsuario', primary_key=True, to='Matcher.Usuario')),
                ('cuenta_idcuenta', models.ForeignKey(db_column='Cuenta_idCuenta', primary_key=True, serialize=False, to='Matcher.Cuenta')),
            ],
            options={
                'db_table': 'Usuario_Cuenta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UsuarioCuentaBk',
            fields=[
                ('usuario_bk_idusuario', models.BigIntegerField(primary_key=True, db_column='Usuario_BK_idUsuario', serialize=False)),
                ('cuenta_bk_idcuenta', models.ForeignKey(db_column='Cuenta_BK_idCuenta', primary_key=True, to='Matcher.CuentaBk')),
            ],
            options={
                'db_table': 'Usuario_Cuenta_BK',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VAbiertasconta',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('codigo', models.CharField(max_length=35, db_column='Codigo')),
                ('origen', models.CharField(max_length=1, db_column='Origen')),
                ('pag_edo', models.BigIntegerField(db_column='Pag_Edo')),
                ('idtransaccion', models.BigIntegerField(db_column='idTransaccion')),
                ('estado_cuenta_idedocuenta', models.BigIntegerField(db_column='Estado_Cuenta_idEdoCuenta')),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(null=True, blank=True, db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=34, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
            ],
            options={
                'db_table': 'v_AbiertasConta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VAbiertascorres',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('idtransaccion', models.BigIntegerField(db_column='idTransaccion')),
                ('estado_cuenta_idedocuenta', models.BigIntegerField(db_column='Estado_Cuenta_idEdoCuenta')),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(null=True, blank=True, db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=34, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('campo86_940', models.CharField(max_length=390, db_column='Campo86_940', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
                ('codigo', models.CharField(max_length=35, db_column='Codigo')),
                ('origen', models.CharField(max_length=1, db_column='Origen')),
                ('pag_edo', models.BigIntegerField(db_column='Pag_Edo')),
            ],
            options={
                'db_table': 'v_AbiertasCorres',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VCerradasconta',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('codigo', models.CharField(max_length=35, db_column='Codigo')),
                ('origen', models.CharField(max_length=1, db_column='Origen')),
                ('pagina', models.BigIntegerField(db_column='Pagina')),
                ('idtransaccion', models.BigIntegerField(db_column='idTransaccion')),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('estado_cuenta_idedocuenta', models.BigIntegerField(null=True, blank=True, db_column='Estado_Cuenta_idEdoCuenta')),
                ('expr1', models.IntegerField(null=True, blank=True, db_column='EXPR1')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('descripcion', models.CharField(max_length=34, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
            ],
            options={
                'db_table': 'v_CerradasConta',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VCerradascorres',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('codigo', models.CharField(max_length=35, db_column='Codigo')),
                ('origen', models.CharField(max_length=1, db_column='Origen')),
                ('pagina', models.BigIntegerField(db_column='Pagina')),
                ('idtransaccion', models.BigIntegerField(db_column='idTransaccion')),
                ('estado_cuenta_idedocuenta', models.BigIntegerField(db_column='Estado_Cuenta_idEdoCuenta')),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('expr1', models.IntegerField(null=True, blank=True, db_column='EXPR1')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=34, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('referencianostro', models.CharField(max_length=16, db_column='ReferenciaNostro', blank=True)),
                ('referenciacorresponsal', models.CharField(max_length=16, db_column='ReferenciaCorresponsal', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('numtransaccion', models.IntegerField(db_column='NumTransaccion')),
                ('seguimiento', models.TextField(blank=True, db_column='Seguimiento')),
            ],
            options={
                'db_table': 'v_CerradasCorres',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VConciliacionconsolidado',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('codigo', models.CharField(max_length=10, db_column='Codigo')),
                ('ref_nostro', models.CharField(max_length=35, db_column='Ref_Nostro')),
                ('ref_vostro', models.CharField(max_length=35, db_column='Ref_Vostro')),
                ('codmoneda', models.CharField(max_length=3, db_column='CodMoneda')),
                ('ultimafechaconciliacion', models.DateTimeField(null=True, blank=True, db_column='UltimaFechaConciliacion')),
                ('tipo_cta', models.IntegerField(null=True, blank=True, db_column='Tipo_Cta')),
                ('idconciliacionconsolidado', models.BigIntegerField(db_column='idConciliacionConsolidado')),
                ('cuenta_idcuenta', models.BigIntegerField(db_column='Cuenta_idCuenta')),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('realizadopor', models.CharField(max_length=60, db_column='RealizadoPor', blank=True)),
            ],
            options={
                'db_table': 'v_ConciliacionConsolidado',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VDistincthistoricos',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('refnostro', models.CharField(max_length=16, db_column='RefNostro', blank=True)),
                ('refvostro', models.CharField(max_length=16, db_column='RefVostro', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('origen', models.CharField(max_length=1, db_column='Origen')),
            ],
            options={
                'db_table': 'v_DISTINCTHistoricos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VHistoricos',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('idhistoricoconsolidado', models.BigIntegerField(db_column='idHistoricoConsolidado')),
                ('fechaconciliacion', models.DateTimeField(db_column='FechaConciliacion')),
                ('totalcreditoscontabilidad', models.FloatField(db_column='TotalCreditosContabilidad')),
                ('totaldebitoscontabilidad', models.FloatField(db_column='TotalDebitosContabilidad')),
                ('totalcreditoscorresponsal', models.FloatField(db_column='TotalCreditosCorresponsal')),
                ('totaldebitoscorresponsal', models.FloatField(db_column='TotalDebitosCorresponsal')),
                ('saldocontabilidad', models.FloatField(db_column='SaldoContabilidad')),
                ('saldocorresponsal', models.FloatField(db_column='SaldoCorresponsal')),
                ('balancefinalcontabilidad', models.FloatField(db_column='BalanceFinalContabilidad')),
                ('balancefinalcorresponsal', models.FloatField(db_column='BalanceFinalCorresponsal')),
                ('diferencia', models.FloatField(db_column='Diferencia')),
                ('autorizadopor', models.CharField(max_length=60, db_column='AutorizadoPor', blank=True)),
                ('firmadopor', models.CharField(max_length=60, db_column='FirmadoPor', blank=True)),
                ('cargofirmante', models.CharField(max_length=60, db_column='CargoFirmante', blank=True)),
                ('realizadopor', models.CharField(max_length=60, db_column='RealizadoPor', blank=True)),
                ('numedo_cont', models.CharField(max_length=35, db_column='NumEdo_Cont', blank=True)),
                ('pag_cont', models.IntegerField(null=True, blank=True, db_column='Pag_Cont')),
                ('fecha_cont', models.DateTimeField(null=True, blank=True, db_column='Fecha_Cont')),
                ('balance_cont', models.FloatField(null=True, blank=True, db_column='Balance_Cont')),
                ('cd_cont', models.CharField(max_length=1, db_column='CD_Cont', blank=True)),
                ('numedo_corr', models.CharField(max_length=35, db_column='NumEdo_Corr', blank=True)),
                ('pag_corr', models.IntegerField(null=True, blank=True, db_column='Pag_Corr')),
                ('fecha_corr', models.DateTimeField(null=True, blank=True, db_column='Fecha_Corr')),
                ('balance_corr', models.FloatField(null=True, blank=True, db_column='Balance_Corr')),
                ('cd_corr', models.CharField(max_length=1, db_column='CD_Corr', blank=True)),
                ('tasa_cambio', models.FloatField(null=True, blank=True, db_column='Tasa_Cambio')),
                ('idhistoricotransacciones', models.BigIntegerField(db_column='idHistoricoTransacciones')),
                ('historicoconsolidado_id', models.BigIntegerField(db_column='HistoricoConsolidado_ID')),
                ('codigo_transaccion', models.CharField(max_length=4, db_column='Codigo_Transaccion')),
                ('pagina', models.IntegerField(db_column='Pagina')),
                ('fecha_valor', models.DateTimeField(db_column='Fecha_Valor')),
                ('descripcion', models.CharField(max_length=45, db_column='Descripcion', blank=True)),
                ('monto', models.FloatField(db_column='Monto')),
                ('credito_debito', models.CharField(max_length=2, db_column='Credito_Debito')),
                ('refvostro', models.CharField(max_length=16, db_column='RefVostro', blank=True)),
                ('refnostro', models.CharField(max_length=16, db_column='RefNostro', blank=True)),
                ('codigocuenta', models.CharField(max_length=10, db_column='CodigoCuenta')),
                ('origen', models.CharField(max_length=1, db_column='Origen')),
                ('observacion', models.CharField(max_length=300, db_column='Observacion', blank=True)),
                ('num_transaccion', models.IntegerField(db_column='Num_Transaccion')),
                ('fecha_salida', models.DateTimeField(null=True, blank=True, db_column='Fecha_Salida')),
                ('numedo', models.CharField(max_length=35, db_column='NumEdo', blank=True)),
            ],
            options={
                'db_table': 'v_Historicos',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa_id_empresa',
            field=models.ForeignKey(db_column='Empresa_Id_Empresa', null=True, blank=True, related_name='Empresa_id', to='Matcher.Empresa'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil_idperfil',
            field=models.ForeignKey(db_column='Perfil_idPerfil', null=True, blank=True, to='Matcher.Perfil'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sesion',
            name='usuario_idusuario',
            field=models.ForeignKey(db_column='Usuario_idUsuario', null=True, blank=True, to='Matcher.Usuario'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reversocerradacorresponsal',
            name='tc_corres',
            field=models.ForeignKey(db_column='TC_Corres_ID', related_name='TC_Corres_ID', to='Matcher.TranscerradaCorresponsal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reversocerradacorresponsal',
            name='tc_corres_id_2',
            field=models.ForeignKey(db_column='TC_Corres_ID_2', related_name='TC_Corres_ID_2', to='Matcher.TranscerradaCorresponsal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reversocerradacontabilidad',
            name='tc_conta',
            field=models.ForeignKey(db_column='TC_Conta_ID', related_name='TC_Conta_ID', to='Matcher.TranscerradaContabilidad'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reversocerradacontabilidad',
            name='tc_conta_id_2',
            field=models.ForeignKey(db_column='TC_Conta_ID_2', related_name='TC_Conta_ID_2', to='Matcher.TranscerradaContabilidad'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reglatransformacionbk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_BK_idCuenta', to='Matcher.CuentaBk'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reglatransformacion',
            name='cuenta_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_idCuenta', to='Matcher.Cuenta'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='observacioncorresponsal',
            name='ta_corres',
            field=models.ForeignKey(db_column='TA_Corres_ID', to='Matcher.TransabiertaCorresponsal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='observacioncontabilidad',
            name='ta_conta',
            field=models.ForeignKey(db_column='TA_Conta_ID', to='Matcher.TransabiertaContabilidad'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mt95',
            name='ta_conta',
            field=models.ForeignKey(db_column='TA_Conta_ID', null=True, blank=True, to='Matcher.TransabiertaContabilidad'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mt95',
            name='ta_corres',
            field=models.ForeignKey(db_column='TA_Corres_ID', null=True, blank=True, to='Matcher.TransabiertaCorresponsal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='matchpropuestos',
            name='ta_conta',
            field=models.ForeignKey(db_column='TA_Conta_ID', null=True, blank=True, to='Matcher.TransabiertaContabilidad'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='matchpropuestos',
            name='ta_corres',
            field=models.ForeignKey(db_column='TA_Corres_ID', null=True, blank=True, to='Matcher.TransabiertaCorresponsal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='matchconfirmado',
            name='tc_conta',
            field=models.ForeignKey(db_column='TC_Conta_ID', null=True, blank=True, to='Matcher.TranscerradaContabilidad'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='matchconfirmado',
            name='tc_corres',
            field=models.ForeignKey(db_column='TC_Corres_ID', null=True, blank=True, to='Matcher.TranscerradaCorresponsal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='formatoarchivobk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_BK_idCuenta', to='Matcher.CuentaBk'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='formatoarchivo',
            name='cuenta_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_idCuenta', to='Matcher.Cuenta'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='estadocuentabk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_BK_idCuenta', null=True, blank=True, to='Matcher.CuentaBk'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='cuenta_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_idCuenta', null=True, blank=True, to='Matcher.Cuenta'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='encajelegalbk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_BK_idCuenta', to='Matcher.CuentaBk'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='encajelegal',
            name='cuenta_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_idCuenta', to='Matcher.Cuenta'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='banco_corresponsal_idbanco',
            field=models.ForeignKey(db_column='Banco_Corresponsal_idBanco', to='Matcher.BancoCorresponsal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='criterios_match_idcriterio',
            field=models.ForeignKey(db_column='Criterios_Match_idCriterio', to='Matcher.CriteriosMatch'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='moneda_idmoneda',
            field=models.ForeignKey(db_column='Moneda_idMoneda', null=True, blank=True, to='Matcher.Moneda'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='conciliacionconsolidadobk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_BK_idCuenta', to='Matcher.CuentaBk'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='conciliacionconsolidado',
            name='cuenta_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_idCuenta', to='Matcher.Cuenta'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alertascuentabk',
            name='cuenta_bk_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_BK_idCuenta', to='Matcher.CuentaBk'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='alertascuenta',
            name='cuenta_idcuenta',
            field=models.ForeignKey(db_column='Cuenta_idCuenta', to='Matcher.Cuenta'),
            preserve_default=True,
        ),
    ]
